import { expect, test } from 'vitest'

import * as treePackage from '@workspace/tree'
import type {
  FileTreeBatchOperation,
  FileTreeCompositionOptions,
  FileTreeContextMenuItem,
  FileTreeContextMenuOpenContext,
  FileTreeDirectoryHandle,
  FileTreeDragAndDropConfig,
  FileTreeDropContext,
  FileTreeDropResult,
  FileTreeDropTarget,
  FileTreeFileHandle,
  FileTreeGitStatusPatch,
  FileTreeInitialExpansion,
  FileTreeItemHandle,
  FileTreeMoveOptions,
  FileTreeMutationEvent,
  FileTreeMutationEventForType,
  FileTreeMutationEventType,
  FileTreeMutationHandle,
  FileTreeMutationSemanticEvent,
  FileTreeOptions,
  FileTreePreparedInput,
  FileTreePublicId,
  FileTreeRemoveOptions,
  FileTreeRenameEvent,
  FileTreeRenamingConfig,
  FileTreeResetOptions,
  FileTreeRowDecoration,
  FileTreeRowDecorationContext,
  FileTreeRowDecorationRenderer,
  FileTreeScrollToPathOptions,
  FileTreeSearchBlurBehavior,
  FileTreeSearchMode,
  FileTreeSearchSessionHandle,
  FileTreeSelectionChangeListener,
  FileTreeSortComparator,
  GitStatus,
  GitStatusEntry,
} from '@workspace/tree'

type PublicTypeAllowlist = readonly [
  FileTreeOptions,
  FileTreePreparedInput,
  FileTreePublicId,
  FileTreeDirectoryHandle,
  FileTreeFileHandle,
  FileTreeItemHandle,
  FileTreeDropTarget,
  FileTreeDropContext,
  FileTreeDropResult,
  FileTreeRenameEvent,
  FileTreeRowDecorationContext,
  FileTreeContextMenuItem,
  FileTreeContextMenuOpenContext,
  FileTreeBatchOperation,
  FileTreeCompositionOptions,
  FileTreeDragAndDropConfig,
  FileTreeGitStatusPatch,
  FileTreeMoveOptions,
  FileTreeMutationEvent,
  FileTreeMutationEventForType<'*'>,
  FileTreeMutationSemanticEvent,
  FileTreeMutationEventType,
  FileTreeMutationHandle,
  FileTreeRemoveOptions,
  FileTreeRenamingConfig,
  FileTreeResetOptions,
  FileTreeRowDecoration,
  FileTreeRowDecorationRenderer,
  FileTreeScrollToPathOptions,
  FileTreeSearchBlurBehavior,
  FileTreeSearchMode,
  FileTreeSearchSessionHandle,
  FileTreeSelectionChangeListener,
  FileTreeSortComparator,
  FileTreeInitialExpansion,
  GitStatus,
  GitStatusEntry,
]

type PublicTypesAreNameable = PublicTypeAllowlist extends readonly unknown[] ? true : false

const publicTypesAreNameable: PublicTypesAreNameable = true

test('exports the model and the helpers the app view renders with', () => {
  expect(Object.keys(treePackage).toSorted()).toEqual([
    'CONTEXT_MENU_TRIGGER_TYPE',
    'FILE_TREE_DEFAULT_ITEM_HEIGHT',
    'FILE_TREE_DEFAULT_OVERSCAN',
    'FILE_TREE_DEFAULT_VIEWPORT_HEIGHT',
    'FileTreeController',
    'GIT_STATUS_DESCENDANT_TITLE',
    'GIT_STATUS_LABEL',
    'GIT_STATUS_TITLE',
    'applyFileTreeGitStatusPatch',
    'arePathSetsEqual',
    'computeFileTreeLayout',
    'computeStickyRows',
    'prepareFileTreeInput',
    'preparePresortedFileTreeInput',
    'resolveFileTreeDensity',
    'resolveFileTreeGitStatusState',
  ])
  expect(publicTypesAreNameable).toBe(true)
})
