import { defineMetadata } from './metadata'

const questionPositions = [1, 2, 3, 4, 5, 6, 7, 8, 9] as const

export const questionCommandMetadata = questionPositions.map((position) =>
  defineMetadata({
    id: `question.select${position}` as const,
    title: `Choose answer ${position}`,
    category: 'Chat',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: true,
  }),
)

export const terminalSendKeystrokeMetadata = defineMetadata({
  id: 'terminal.sendKeystroke',
  title: 'Send terminal keystroke',
  description: 'Send the preset keystroke or text to the focused shell.',
  category: 'Terminal',
  execution: 'sync',
  target: 'workspace',
  undoCategory: 'view-only',
  when: [],
  hiddenInPalette: true,
})

export type TerminalSendKeystrokeArgs =
  | { readonly keystroke: string; readonly text?: never }
  | { readonly text: string; readonly keystroke?: never }

export const localCommandMetadata = [
  defineMetadata({
    id: 'chat.pasteAsText',
    title: 'Paste as text',
    category: 'Chat',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: true,
  }),
  defineMetadata({
    id: 'fileTree.selectAll',
    title: 'Select all files',
    category: 'Files',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: false,
  }),
  defineMetadata({
    id: 'fileTree.toggleMark',
    title: 'Mark selected file',
    category: 'Files',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: false,
  }),
  defineMetadata({
    id: 'filePicker.navigateBack',
    title: 'Previous folder',
    category: 'Files',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: true,
  }),
  defineMetadata({
    id: 'filePicker.navigateForward',
    title: 'Next folder',
    category: 'Files',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: true,
  }),
  defineMetadata({
    id: 'filePicker.openSelected',
    title: 'Open selected entry',
    category: 'Files',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: true,
  }),
  defineMetadata({
    id: 'filePicker.goToFolder',
    title: 'Go to folder',
    category: 'Files',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: true,
  }),
  defineMetadata({
    id: 'filePicker.toggleHidden',
    title: 'Show hidden files',
    category: 'Files',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: true,
  }),
  defineMetadata({
    id: 'filePicker.goUp',
    title: 'Parent folder',
    category: 'Files',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: true,
  }),
  defineMetadata({
    id: 'themeStudio.close',
    title: 'Close Theme Studio',
    category: 'Settings',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: true,
  }),
  defineMetadata({
    id: 'themeStudio.toggleMode',
    title: 'Change Theme Studio mode',
    category: 'Settings',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: true,
  }),
  defineMetadata({
    id: 'themeStudio.apply',
    title: 'Apply theme changes',
    category: 'Settings',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: true,
  }),
  defineMetadata({
    id: 'terminal.rename',
    title: 'Rename terminal',
    category: 'Terminal',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: false,
  }),
  defineMetadata({
    id: 'terminal.selectAll',
    title: 'Select terminal text',
    category: 'Terminal',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: false,
  }),
  defineMetadata({
    id: 'terminal.fontSizeIncrease',
    title: 'Increase terminal font size',
    category: 'Terminal',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: false,
  }),
  defineMetadata({
    id: 'terminal.fontSizeDecrease',
    title: 'Decrease terminal font size',
    category: 'Terminal',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: false,
  }),
  defineMetadata({
    id: 'terminal.fontSizeReset',
    title: 'Reset terminal font size',
    category: 'Terminal',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    hiddenInPalette: false,
  }),
]
