import { defineMetadata, type CommandKeyDefault } from './metadata'
import { sessionJumpCommandId, type SessionJumpPosition } from './session-jump'

export const workspaceCommandMetadata = {
  'workspace.undoWorkspaceEdit': defineMetadata({
    category: 'Workspace',
    description: 'Undo the latest atomic multi-file workspace edit.',
    id: 'workspace.undoWorkspaceEdit',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: ['workspaceOpen', 'workspaceEditUndoable'],
    title: 'Undo workspace edit',
  }),
  'workspace.redoWorkspaceEdit': defineMetadata({
    category: 'Workspace',
    description: 'Redo the latest atomic multi-file workspace edit.',
    id: 'workspace.redoWorkspaceEdit',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: ['workspaceOpen', 'workspaceEditRedoable'],
    title: 'Redo workspace edit',
  }),
  'workspace.undoSessionAction': defineMetadata({
    category: 'Workspace',
    description: 'Undo the settle, snooze, unpin or archive named in the notice.',
    id: 'workspace.undoSessionAction',
    execution: 'async',
    // Every pane without its own undo; the composer, editors, terminals and the file tree keep theirs.
    // The terminal keeps Control+Z for suspend, so the TUI rail takes U.
    keys: [
      ...(['global', 'git', 'logs', 'problems', 'search', 'settings'] as const).map(
        (pane): CommandKeyDefault => ({
          chord: ['Mod+Z'],
          pane,
          preventDefault: true,
          yieldsToTextEntry: true,
        }),
      ),
      { chord: ['U'], pane: 'chat', platforms: ['tui'] },
    ],
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: ['sessionActionUndoable'],
    title: 'Undo session action',
  }),
  'fileTree.undo': defineMetadata({
    category: 'Workspace',
    description: 'Undo the latest move, rename, create, duplicate or delete in the file tree.',
    id: 'fileTree.undo',
    execution: 'async',
    keys: [{ chord: ['Mod+Z'], pane: 'file-tree', preventDefault: true, yieldsToTextEntry: true }],
    target: 'workspace',
    undoCategory: 'file-operation',
    when: ['workspaceOpen', 'fileOperationUndoable'],
    title: 'Undo file operation',
  }),
  'fileTree.redo': defineMetadata({
    category: 'Workspace',
    description: 'Redo the file tree operation undone last.',
    id: 'fileTree.redo',
    execution: 'async',
    keys: [
      { chord: ['Mod+Shift+Z'], pane: 'file-tree', preventDefault: true, yieldsToTextEntry: true },
    ],
    target: 'workspace',
    undoCategory: 'file-operation',
    when: ['workspaceOpen', 'fileOperationRedoable'],
    title: 'Redo file operation',
  }),
  'workspace.showQuickAccess': defineMetadata({
    category: 'Workspace',
    description: 'Search workspace files and quick actions.',
    id: 'workspace.showQuickAccess',
    keepsPaletteOpen: true,
    keys: [
      {
        chord: ['Mod+P'],
        preventDefault: true,
        stopPropagation: true,
        vscodeCommandId: 'workbench.action.quickOpen',
      },
      { chord: ['Control+P'], platforms: ['tui'] },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Quick Open',
    vscodeCommandIds: ['workbench.action.quickOpen'],
  }),
  'workspace.showCommandPalette': defineMetadata({
    category: 'Workspace',
    description: 'Search and run workspace or editor commands.',
    hiddenInPalette: true,
    id: 'workspace.showCommandPalette',
    keepsPaletteOpen: true,
    keys: [
      {
        chord: ['Mod+Shift+P'],
        preventDefault: true,
        stopPropagation: true,
        vscodeCommandId: 'workbench.action.showCommands',
      },
      {
        chord: ['F1'],
        preventDefault: true,
        stopPropagation: true,
        vscodeCommandId: 'workbench.action.showCommands',
      },
      { chord: ['F1'], platforms: ['tui'] },
      { chord: ['Control+K', 'P'], platforms: ['tui'] },
      { chord: ['Control+Shift+P'], platforms: ['tui'], terminalProtocol: 'kitty' },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Show command palette',
    vscodeCommandIds: ['workbench.action.showCommands'],
  }),
  'workspace.selectAppColors': defineMetadata({
    category: 'Appearance',
    description: 'Choose colors for app backgrounds, text, borders, and accents.',
    id: 'workspace.selectAppColors',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Choose app colors',
    keepsPaletteOpen: true,
  }),
  'workspace.runProjectScript': defineMetadata({
    category: 'Workspace',
    description: 'Choose and run a script from this project.',
    id: 'workspace.runProjectScript',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen', 'workspaceMutable'],
    title: 'Run project script',
    keepsPaletteOpen: true,
  }),
  'workspace.switchSession': defineMetadata({
    category: 'Workspace',
    description: 'Find and open a chat session.',
    id: 'workspace.switchSession',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Switch session',
    keepsPaletteOpen: true,
  }),
  'workspace.showUnicodeSettings': defineMetadata({
    category: 'Editor',
    description: 'Configure Unicode character highlighting and exclusions.',
    id: 'workspace.showUnicodeSettings',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Open Unicode highlight settings',
  }),
  'workspace.showFontSettings': defineMetadata({
    category: 'Appearance',
    description: 'Change the editor and terminal font.',
    id: 'workspace.showFontSettings',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Open font settings',
  }),
  'workspace.cloneRepository': defineMetadata({
    category: 'Git',
    description: 'Clone a repository into a new folder and open it as a project.',
    id: 'workspace.cloneRepository',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Clone repository…',
  }),
  'workspace.startPullRequestSession': defineMetadata({
    category: 'Git',
    description: "Start a session in its own worktree at a pull request's head.",
    id: 'workspace.startPullRequestSession',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Start session from pull request…',
  }),
  'workspace.showUsage': defineMetadata({
    category: 'Chat',
    description: 'See what each model cost, by day, and set prices for models that report none.',
    id: 'workspace.showUsage',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Open usage',
  }),
  'workspace.showTransparencySettings': defineMetadata({
    category: 'Appearance',
    description: 'Change pane transparency and backdrop appearance.',
    id: 'workspace.showTransparencySettings',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Open transparency settings',
  }),
  'workspace.showSettings': defineMetadata({
    category: 'Workspace',
    description: 'Open providers, models, and keybindings.',
    id: 'workspace.showSettings',
    keys: [
      {
        chord: ['Mod+,'],
        preventDefault: true,
        stopPropagation: true,
        vscodeCommandId: 'workbench.action.openSettings',
      },
      { chord: ['Mod+K', 'Mod+S'], vscodeCommandId: 'workbench.action.openGlobalKeybindings' },
      { chord: ['Control+K', 'S'], platforms: ['tui'] },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Settings',
    vscodeCommandIds: ['workbench.action.openSettings'],
  }),
  'workspace.openFilePicker': defineMetadata({
    category: 'Workspace',
    description: 'Open the workspace file picker.',
    id: 'workspace.openFilePicker',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Open file picker',
    vscodeCommandIds: ['workbench.action.quickOpen'],
  }),
  'workspace.openSearchEditor': defineMetadata({
    keys: [{ chord: ['Control+K', 'F'], platforms: ['tui'] }],
    category: 'Workspace',
    description: 'Open workspace search results in an editor tab.',
    id: 'workspace.openSearchEditor',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Open Search Editor',
    vscodeCommandIds: ['search.action.openNewEditor'],
  }),
  'workspace.quickOpenPreviousEditor': defineMetadata({
    category: 'Workspace',
    description: 'Switch to the previously active editor.',
    id: 'workspace.quickOpenPreviousEditor',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Quick open previous editor',
    vscodeCommandIds: ['workbench.action.quickOpenPreviousEditor'],
  }),
  'workspace.quickOpenView': defineMetadata({
    keys: [{ chord: ['Control+K', 'V'], platforms: ['tui'] }],
    category: 'Workspace',
    description: 'Search and focus workspace views.',
    id: 'workspace.quickOpenView',
    keepsPaletteOpen: true,
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Open view',
    vscodeCommandIds: ['workbench.action.quickOpenView'],
  }),
  'workspace.gotoSymbol': defineMetadata({
    category: 'Workspace',
    description: 'Search symbols in the active editor.',
    id: 'workspace.gotoSymbol',
    keepsPaletteOpen: true,
    keys: [
      {
        chord: ['Mod+Shift+O'],
        preventDefault: true,
        vscodeCommandId: 'workbench.action.gotoSymbol',
      },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['fileBackedTab'],
    title: 'Go to symbol in editor',
    vscodeCommandIds: ['workbench.action.gotoSymbol'],
  }),
  'workspace.showAllEditors': defineMetadata({
    category: 'Workspace',
    description: 'Search open editor tabs.',
    id: 'workspace.showAllEditors',
    keepsPaletteOpen: true,
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Show all editors',
    vscodeCommandIds: ['workbench.action.showAllEditors'],
  }),
  'workspace.saveFile': defineMetadata({
    category: 'Workspace',
    description: 'Save the active editor.',
    id: 'workspace.saveFile',
    keys: [
      { chord: ['Mod+S'], preventDefault: true, vscodeCommandId: 'workbench.action.files.save' },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'file-operation',
    when: ['saveableTab', 'workspaceMutable'],
    title: 'Save',
    vscodeCommandIds: ['workbench.action.files.save'],
  }),
  'workspace.saveAllFiles': defineMetadata({
    category: 'Workspace',
    description: 'Save all dirty editors.',
    id: 'workspace.saveAllFiles',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'file-operation',
    when: ['workspaceOpen', 'workspaceMutable'],
    title: 'Save all',
    vscodeCommandIds: ['workbench.action.files.saveAll'],
  }),
  'workspace.compareWithSaved': defineMetadata({
    category: 'Workspace',
    description: 'Diff the active editor against the file on disk.',
    id: 'workspace.compareWithSaved',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['fileBackedTab'],
    title: 'Compare with saved',
    vscodeCommandIds: ['workbench.files.action.compareWithSaved'],
  }),
  'workspace.showHistory': defineMetadata({
    category: 'Workspace',
    description: "Browse, compare and restore the active file's undo history.",
    id: 'workspace.showHistory',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['fileBackedTab'],
    title: 'Show history',
  }),
  'workspace.historyBack': defineMetadata({
    category: 'Workspace',
    description: 'Step to the previous editor state in time, across undo branches.',
    id: 'workspace.historyBack',
    execution: 'async',
    keys: [{ chord: ['Mod+Alt+Z'], pane: 'editor', preventDefault: true }],
    target: 'workspace',
    undoCategory: 'text-edit',
    when: ['fileBackedTab'],
    title: 'History: back',
  }),
  'workspace.historyForward': defineMetadata({
    category: 'Workspace',
    description: 'Step to the next editor state in time, across undo branches.',
    id: 'workspace.historyForward',
    execution: 'async',
    keys: [{ chord: ['Mod+Alt+Shift+Z'], pane: 'editor', preventDefault: true }],
    target: 'workspace',
    undoCategory: 'text-edit',
    when: ['fileBackedTab'],
    title: 'History: forward',
  }),
  'workspace.openFileAtHead': defineMetadata({
    category: 'Workspace',
    description: 'Open the committed version of the active file, read-only.',
    id: 'workspace.openFileAtHead',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['fileBackedTab'],
    title: 'Open file at HEAD',
    vscodeCommandIds: ['git.openFile'],
  }),
  'workspace.revertFile': defineMetadata({
    category: 'Workspace',
    description: 'Reload the active editor from disk.',
    id: 'workspace.revertFile',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'file-operation',
    when: ['fileBackedTab'],
    title: 'Revert file',
    vscodeCommandIds: ['workbench.action.files.revert'],
  }),
  'workspace.reopenClosedEditor': defineMetadata({
    category: 'Workspace',
    description: 'Reopen the most recently closed editor tab.',
    id: 'workspace.reopenClosedEditor',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Reopen closed editor',
    vscodeCommandIds: ['workbench.action.reopenClosedEditor'],
  }),
  'workspace.toggleSidebarVisibility': defineMetadata({
    category: 'Workspace',
    description: 'Show or hide the Files pane.',
    id: 'workspace.toggleSidebarVisibility',
    keys: [
      {
        chord: ['Mod+B'],
        preventDefault: true,
        vscodeCommandId: 'workbench.action.toggleSidebarVisibility',
      },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Toggle Files pane',
    vscodeCommandIds: ['workbench.action.toggleSidebarVisibility'],
  }),
  'workspace.togglePanel': defineMetadata({
    category: 'Workspace',
    description: 'Show or hide the active workspace panel.',
    id: 'workspace.togglePanel',
    keys: [
      {
        chord: ['Mod+J'],
        preventDefault: true,
        vscodeCommandId: 'workbench.action.togglePanel',
      },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Toggle panel',
    vscodeCommandIds: ['workbench.action.togglePanel'],
  }),
  'workspace.splitEditorRight': defineMetadata({
    category: 'Workspace',
    description: 'Open the selected editor in a new group to the right.',
    id: 'workspace.splitEditorRight',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Split Editor Right',
    vscodeCommandIds: ['workbench.action.splitEditorRight'],
  }),
  'workspace.splitEditorDown': defineMetadata({
    category: 'Workspace',
    description: 'Open the selected editor in a new group below.',
    id: 'workspace.splitEditorDown',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Split Editor Down',
    vscodeCommandIds: ['workbench.action.splitEditorDown'],
  }),
  'workspace.moveTabToGroup': defineMetadata({
    category: 'Workspace',
    description: 'Choose another group for the selected tab.',
    id: 'workspace.moveTabToGroup',
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Move Tab to Group…',
  }),
  'workspace.focusFirstEditorGroup': defineMetadata({
    category: 'Workspace',
    description: 'Focus the first editor group.',
    id: 'workspace.focusFirstEditorGroup',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Focus First Editor Group',
    vscodeCommandIds: ['workbench.action.focusFirstEditorGroup'],
  }),
  'workspace.focusSecondEditorGroup': defineMetadata({
    category: 'Workspace',
    description: 'Focus the second editor group.',
    id: 'workspace.focusSecondEditorGroup',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Focus Second Editor Group',
    vscodeCommandIds: ['workbench.action.focusSecondEditorGroup'],
  }),
  'workspace.focusThirdEditorGroup': defineMetadata({
    category: 'Workspace',
    description: 'Focus the third editor group.',
    id: 'workspace.focusThirdEditorGroup',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Focus Third Editor Group',
    vscodeCommandIds: ['workbench.action.focusThirdEditorGroup'],
  }),
  'workspace.focusEditor': defineMetadata({
    keys: [{ chord: ['Control+K', 'I'], platforms: ['tui'] }],
    category: 'Workspace',
    description: 'Move keyboard focus to the editor.',
    id: 'workspace.focusEditor',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Focus editor',
  }),
  'workspace.focusFileTree': defineMetadata({
    category: 'Workspace',
    description: 'Move keyboard focus to the file tree.',
    id: 'workspace.focusFileTree',
    keys: [
      { chord: ['Mod+Shift+E'], preventDefault: true },
      { chord: ['Control+K', 'E'], platforms: ['tui'] },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Focus file tree',
  }),
  'workspace.findInFileTree': defineMetadata({
    category: 'Workspace',
    description: 'Filter the loaded files in the file tree.',
    id: 'workspace.findInFileTree',
    keys: [{ chord: ['Mod+F'], pane: 'file-tree', preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Filter files in tree',
  }),
  'workspace.revealActiveFileInTree': defineMetadata({
    category: 'Workspace',
    description: 'Focus and reveal the active editor file in the file tree.',
    id: 'workspace.revealActiveFileInTree',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['fileBackedTab'],
    title: 'Reveal active file in tree',
  }),
  'workspace.focusGit': defineMetadata({
    keys: [{ chord: ['Control+K', 'G'], platforms: ['tui'] }],
    category: 'Workspace',
    description: 'Move keyboard focus to the Git panel.',
    id: 'workspace.focusGit',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Focus Git',
  }),
  'workspace.copyAddress': defineMetadata({
    category: 'Workspace',
    description:
      'Copy a link to exactly where you are — no absolute paths, no dev-only parameters.',
    id: 'workspace.copyAddress',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: ['workspaceOpen'],
    title: 'Copy address',
  }),
  'workspace.navigateBack': defineMetadata({
    category: 'Workspace',
    description: 'Go back to the previous document.',
    id: 'workspace.navigateBack',
    keys: [{ chord: ['Mod+['] }, { chord: ['Control+K', 'B'], platforms: ['tui'] }],
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Back',
  }),
  'workspace.navigateForward': defineMetadata({
    category: 'Workspace',
    description: 'Go forward again.',
    id: 'workspace.navigateForward',
    keys: [{ chord: ['Mod+]'] }, { chord: ['Control+K', 'N'], platforms: ['tui'] }],
    execution: 'sync',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Forward',
  }),
  'workspace.revealChat': defineMetadata({
    category: 'Workspace',
    description: 'Bring the chat composer on screen.',
    id: 'workspace.revealChat',
    keys: [{ chord: ['Control+K', 'R'], platforms: ['tui'] }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Show chat',
  }),
  'workspace.revealTerminal': defineMetadata({
    keys: [{ chord: ['Control+K', 'T'], platforms: ['tui'] }],
    category: 'Workspace',
    description: 'Bring the workbench terminal on screen.',
    id: 'workspace.revealTerminal',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Show terminal',
  }),
  'workspace.newTerminal': defineMetadata({
    category: 'Workspace',
    description: 'Open another terminal tab in the workbench panel.',
    id: 'workspace.newTerminal',
    keys: [
      {
        chord: ['Mod+`'],
        preventDefault: true,
        vscodeCommandId: 'workbench.action.terminal.new',
      },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'New terminal',
    vscodeCommandIds: ['workbench.action.terminal.new'],
  }),
  'workspace.killTerminal': defineMetadata({
    category: 'Workspace',
    description: 'Close the active terminal tab and end its shell.',
    id: 'workspace.killTerminal',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Kill active terminal',
    vscodeCommandIds: ['workbench.action.terminal.kill'],
  }),
  'workspace.focusNextTerminal': defineMetadata({
    category: 'Workspace',
    description: 'Switch to the next terminal tab.',
    id: 'workspace.focusNextTerminal',
    keys: [{ chord: ['Mod+PageDown'], pane: 'terminal', preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Focus next terminal',
    vscodeCommandIds: ['workbench.action.terminal.focusNext'],
  }),
  'workspace.focusPreviousTerminal': defineMetadata({
    category: 'Workspace',
    description: 'Switch to the previous terminal tab.',
    id: 'workspace.focusPreviousTerminal',
    keys: [{ chord: ['Mod+PageUp'], pane: 'terminal', preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Focus previous terminal',
    vscodeCommandIds: ['workbench.action.terminal.focusPrevious'],
  }),
  'workspace.closeCurrentTab': defineMetadata({
    category: 'Workspace',
    description: 'Close the selected editor tab.',
    id: 'workspace.closeCurrentTab',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['tabOpen'],
    title: 'Close current tab',
    vscodeCommandIds: ['workbench.action.closeActiveEditor'],
  }),
  'workspace.newChat': defineMetadata({
    category: 'Chat',
    description: 'Open a fresh chat draft, in the Chat panel or on the chat stage.',
    id: 'workspace.newChat',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Start a new chat',
  }),
  'workspace.acceptCommitMessage': defineMetadata({
    category: 'Git',
    description: 'Save COMMIT_EDITMSG, close it, and commit with what it says.',
    id: 'workspace.acceptCommitMessage',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: ['fileBackedTab', 'workspaceMutable'],
    title: 'Accept commit message',
    vscodeCommandIds: ['git.commitMessageAccept'],
  }),
  'workspace.discardCommitMessage': defineMetadata({
    category: 'Git',
    description: 'Close COMMIT_EDITMSG without committing.',
    id: 'workspace.discardCommitMessage',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['fileBackedTab'],
    title: 'Discard commit message',
    vscodeCommandIds: ['git.commitMessageDiscard'],
  }),
  'workspace.toggleDiffViewMode': defineMetadata({
    category: 'Workspace',
    description: 'Switch the active diff viewer between split and unified modes.',
    id: 'workspace.toggleDiffViewMode',
    keys: [{ chord: ['Mod+Shift+D'] }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: ['workspaceOpen'],
    title: 'Toggle diff view mode',
  }),
  'workspace.toggleUiMode': defineMetadata({
    category: 'Workspace',
    description: 'Switch between the Workbench and Chat layouts.',
    id: 'workspace.toggleUiMode',
    keys: [{ chord: ['Mod+Shift+M'], preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Toggle Chat mode',
  }),
  'workspace.showChatMode': defineMetadata({
    category: 'Workspace',
    description: 'Show sessions, chat, and tools in the chat layout.',
    id: 'workspace.showChatMode',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Chat mode',
  }),
  'workspace.showWorkbenchMode': defineMetadata({
    category: 'Workspace',
    description: 'Show the editor-centred workbench layout.',
    id: 'workspace.showWorkbenchMode',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen'],
    title: 'Workbench mode',
  }),
  'workspace.selectColorMode': defineMetadata({
    category: 'Appearance',
    description: 'Choose light or dark mode, or follow the system.',
    id: 'workspace.selectColorMode',
    keepsPaletteOpen: true,
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Choose light / dark mode',
  }),
  'workspace.selectColorTheme': defineMetadata({
    category: 'Appearance',
    description: 'Choose colors for the editor and code blocks in chat.',
    id: 'workspace.selectColorTheme',
    keepsPaletteOpen: true,
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Choose code theme',
  }),
  'workspace.setDarkTheme': defineMetadata({
    category: 'Appearance',
    description: 'Use dark mode.',
    hiddenInPalette: true,
    id: 'workspace.setDarkTheme',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: [],
    title: 'Dark mode',
  }),
  'workspace.setLightTheme': defineMetadata({
    category: 'Appearance',
    description: 'Use light mode.',
    hiddenInPalette: true,
    id: 'workspace.setLightTheme',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: [],
    title: 'Light mode',
  }),
  'workspace.setSystemTheme': defineMetadata({
    category: 'Appearance',
    description: 'Follow the system light or dark mode.',
    hiddenInPalette: true,
    id: 'workspace.setSystemTheme',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: [],
    title: 'Follow system light / dark mode',
  }),
  'workspace.selectThemeBundle': defineMetadata({
    aliases: ['Theme bundle'],
    category: 'Appearance',
    description: 'Switch the whole look at once: palette, code theme and wallpaper.',
    id: 'workspace.selectThemeBundle',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Choose theme',
    keepsPaletteOpen: true,
  }),
  'workspace.selectWallpaper': defineMetadata({
    category: 'Appearance',
    description: 'Choose the wallpaper, previewing as you go.',
    id: 'workspace.selectWallpaper',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: [],
    title: 'Choose wallpaper',
    keepsPaletteOpen: true,
  }),
  'wallpaper.next': defineMetadata({
    category: 'Appearance',
    description: 'Select the next library wallpaper.',
    id: 'wallpaper.next',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: [],
    title: 'Next wallpaper',
  }),
  'workspace.toggleWallpaper': defineMetadata({
    category: 'Appearance',
    description: 'Show or hide the background image or video.',
    id: 'workspace.toggleWallpaper',
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: [],
    title: 'Toggle wallpaper',
  }),
  'workspace.newSession': defineMetadata({
    category: 'Workspace',
    description: 'Start a new chat session in the active project.',
    id: 'workspace.newSession',
    keys: [
      { chord: ['Mod+Alt+N'], preventDefault: true },
      { chord: ['Control+N'], platforms: ['tui'] },
    ],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'workspace-operation',
    when: ['workspaceOpen', 'chatMode'],
    title: 'New session',
  }),
  'workspace.nextSession': defineMetadata({
    category: 'Workspace',
    description: 'Move to the next session in the rail.',
    id: 'workspace.nextSession',
    keys: [{ chord: ['Mod+Alt+]'], preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen', 'chatMode'],
    title: 'Next session',
  }),
  'workspace.previousSession': defineMetadata({
    category: 'Workspace',
    description: 'Move to the previous session in the rail.',
    id: 'workspace.previousSession',
    keys: [{ chord: ['Mod+Alt+['], preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen', 'chatMode'],
    title: 'Previous session',
  }),
  'workspace.toggleSessionRail': defineMetadata({
    category: 'Workspace',
    description: 'Show or hide the list of sessions.',
    id: 'workspace.toggleSessionRail',
    keys: [{ chord: ['Mod+Alt+B'], preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen', 'chatMode'],
    title: 'Toggle session rail',
  }),
}
export function sessionJumpMetadata(position: SessionJumpPosition) {
  return defineMetadata({
    category: 'Workspace',
    description: `Put session ${position} in the rail on the stage.`,
    hiddenInPalette: true,
    id: sessionJumpCommandId(position),
    keys: [{ chord: [`Mod+Alt+${position}`], preventDefault: true }],
    execution: 'async',
    target: 'workspace',
    undoCategory: 'view-only',
    when: ['workspaceOpen', 'chatMode'],
    title: `Go to session ${position}`,
  })
}
