import { createRequire } from 'node:module'
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { bundledLanguagesInfo } from 'shiki/langs'
import { TREE_SITTER_LANGUAGE_METADATA } from '@singapore-editor/tree-sitter-languages/metadata'
import { createScriptError } from '../../../scripts/structured-errors'
import candidates from '../../../scripts/syntax/candidates.json'

const require = createRequire(new URL('../package.json', import.meta.url))
const shikiVersion: string = require('shiki/package.json').version
const native = new Map<string, (typeof TREE_SITTER_LANGUAGE_METADATA)[number]>(
  TREE_SITTER_LANGUAGE_METADATA.map((language) => [language.id, language]),
)
const rows = bundledLanguagesInfo.map((language) => {
  const entry = native.get(language.id === 'jsx' ? 'javascript' : language.id)
  const candidate = Object.entries(candidates.languages).find(([id]) => id === language.id)?.[1]
  if (!candidate) throw createScriptError(`Missing inventory row for Shiki ${language.id}`)
  if (!entry)
    return { id: language.id, aliases: language.aliases ?? [], ...candidate, capabilities: null }
  return {
    id: language.id,
    aliases: language.aliases ?? [],
    nativeId: entry.id,
    state: 'partial',
    capabilities: entry.capabilities,
    evidence: 'Editor: test/admission.test.ts; test/native-coverage.browser.test.ts',
    gap: gapFor(entry.id),
    nextAction:
      'Broaden expected-category and edit fixtures; verify remaining embedded languages and structural capabilities.',
  }
})
const counts = Object.fromEntries(
  ['verified', 'partial', 'candidate', 'blocked'].map((state) => [
    state,
    rows.filter((row) => row.state === state).length,
  ]),
)
const report = {
  shikiVersion,
  canonicalCount: rows.length,
  counts,
  specialModes: [
    { id: 'text', state: 'not-a-parser', aliases: ['txt', 'plain', 'plaintext'] },
    { id: 'ansi', state: 'not-a-parser', aliases: [] },
  ],
  rows,
}
const markdown = `# Native syntax coverage\n\nGenerated by \`bun run syntax:coverage\`. Shiki ${shikiVersion}: ${rows.length} canonical IDs.\n\n${JSON.stringify(counts)}\n\n“Partial” means the shipped parser passes the listed fixtures, not TextMate parity. Highlighting, injections, detection and folds are tracked separately. Plain text and ANSI are special modes, not missing grammars. Candidate rows record discovery, not completed admission.\n\n| Shiki ID | State | Evidence / remaining work |\n| --- | --- | --- |\n${rows.map((row) => `| ${row.id} | ${row.state} | ${row.gap} ${row.nextAction} |`).join('\n')}\n`
await output('../../../docs/native-syntax-coverage.json', JSON.stringify(report, null, 2) + '\n')
await output('../../../docs/native-syntax-coverage.md', markdown)
console.log(`Shiki ${shikiVersion}: ${rows.length} IDs; ${JSON.stringify(counts)}`)

function gapFor(id: string): string {
  if (['javascript', 'typescript', 'tsx'].includes(id))
    return 'Builtin shadowing needs local-scope predicates; regex and jsdoc injections are unavailable.'
  if (id === 'astro')
    return 'CSS and TypeScript injections work; SCSS and full Astro expression coverage remain unverified.'
  if (id === 'svelte')
    return 'JavaScript/TypeScript and CSS injections work; preprocessors and Svelte-version parity remain unverified.'
  if (id === 'php') return 'phpdoc and unadmitted heredoc languages remain unavailable.'
  if (id === 'markdown')
    return 'Fences load admitted grammars lazily; unsupported fence languages remain unavailable.'
  return 'Curated captures and worker edits pass; full language coverage and folds are not established.'
}

async function output(path: string, text: string) {
  const url = new URL(path, import.meta.url)
  const formatter = Bun.spawn(
    [
      fileURLToPath(new URL('../../../node_modules/.bin/oxfmt', import.meta.url)),
      '--stdin-filepath',
      fileURLToPath(url),
    ],
    { stdin: new Blob([text]), stdout: 'pipe', stderr: 'pipe' },
  )
  text = await new Response(formatter.stdout).text()
  if ((await formatter.exited) !== 0)
    throw createScriptError(await new Response(formatter.stderr).text())
  if (!process.argv.includes('--check')) return writeFile(url, text)
  if ((await readFile(url, 'utf8')) !== text)
    throw createScriptError(`Stale syntax inventory: ${fileURLToPath(url)}`)
}
