import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { defaultConfig, mergeConfigs } from 'cn/config'
import { compileToSource } from 'cn/compiler'

const root = path.resolve(import.meta.dirname, '../../..')
const output = path.resolve(import.meta.dirname, '../src/lib/generated/cn-tables.ts')
const config = mergeConfigs(defaultConfig(), {
  extend: {
    classGroups: {
      'focus-ring': [
        'focus-ring',
        'focus-ring-within',
        'focus-ring-inset',
        'focus-ring-inset-drawn',
      ],
    },
  },
})
const source = compileToSource(config, {
  lang: 'ts',
  banner: '// Generated by bun run --cwd packages/ui build. Do not edit.',
})
const formatted = spawnSync(
  path.join(root, 'node_modules/.bin/oxfmt'),
  [`--stdin-filepath=${output}`],
  { cwd: root, input: source, encoding: 'utf8' },
)
if (formatted.status !== 0) {
  console.error(`Class table formatter failed (${formatted.status ?? 'no exit status'}).`)
  process.exit(1)
}

const expected = formatted.stdout.toString()
const actual = existsSync(output) ? readFileSync(output, 'utf8') : ''
if (process.argv.includes('--check') && actual !== expected) {
  console.error('Class merge tables are stale. Run bun run --cwd packages/ui build.')
  process.exit(1)
}
if (!process.argv.includes('--check') && actual !== expected) writeFileSync(output, expected)
