/**
 * Projects the pinned `@pierre/vscode-icons` pack, the Catppuccin icons for types the pack lacks,
 * and `rules.ts` into the app's file icons:
 * the glyph file, the name and extension maps with each rule's hue, and the hue tokens.
 * `--check` fails when an output drifts from its inputs.
 *
 * Modelled on `packages/trees/scripts/generate-built-in-icons.ts` in pierrecomputer/pierre at
 * cc4963a (Apache-2.0): the SVG inner extraction and the walk over the pack's theme tiers.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { palette } from '@pierre/vscode-icons/scripts/palette.mjs'
import complete from '@pierre/vscode-icons/scripts/themes/complete.mjs'
import defaultTier from '@pierre/vscode-icons/scripts/themes/default.mjs'
import minimal from '@pierre/vscode-icons/scripts/themes/minimal.mjs'

import { createScriptError } from '../structured-errors'

import {
  CATPPUCCIN_HUES,
  CATPPUCCIN_RULES,
  HUES,
  LIGHT_OVERRIDES,
  LOCAL_HUES,
  PACK_EXTENSIONS_THAT_ARE_FILE_NAMES,
  PACK_NAME_ALIASES,
  RULES,
  type IconHue,
  type IconRule,
} from './rules'

const root = path.join(import.meta.dirname, '..', '..')
const pack = path.dirname(fileURLToPath(import.meta.resolve('@pierre/vscode-icons/package.json')))
const outputs = {
  glyphs: path.join(root, 'apps/web/src/lib/vscode-icon-glyphs.ts'),
  rules: path.join(root, 'apps/web/src/lib/file-icon-rules.generated.ts'),
  css: path.join(root, 'packages/ui/src/styles/file-icons.generated.css'),
}
const GRADIENT_PREFIX = 'app-vscode-icon-'
const CATPPUCCIN_PREFIX = 'catppuccin-'
const HEADER =
  'Generated by scripts/icons/generate.ts from @pierre/vscode-icons, @iconify-json/catppuccin and scripts/icons/rules.ts. Do not edit.'

const tiers = [complete, defaultTier, minimal]

const catppuccin = JSON.parse(
  readFileSync(fileURLToPath(import.meta.resolve('@iconify-json/catppuccin/icons.json')), 'utf8'),
) as { readonly icons: Readonly<Record<string, { readonly body: string }>> }

const packGlyphNames = readdirSync(path.join(pack, 'svgs'))
  .filter((file) => file.endsWith('.svg'))
  .toSorted(compareNames)
  .map((file) => file.slice(0, -'.svg'.length))
const glyphs = new Map([
  ...packGlyphNames.map((name) => [name, readGlyph(name)] as const),
  ...Object.values(CATPPUCCIN_RULES)
    .map((rule) => rule.icon)
    .toSorted(compareNames)
    .map((icon) => [`${CATPPUCCIN_PREFIX}${icon}`, catppuccinGlyph(icon)] as const),
])
const glyphNames = [...glyphs.keys()]

const rules = resolvedRules()
const maps = ruleMaps(rules)

const files = {
  glyphs: formatted(outputs.glyphs, glyphFile()),
  rules: formatted(outputs.rules, rulesFile()),
  css: formatted(outputs.css, cssFile()),
}

if (process.argv.includes('--check')) {
  const stale = (Object.keys(files) as (keyof typeof files)[]).filter(
    (key) => readFileSync(outputs[key], 'utf8') !== files[key],
  )
  if (stale.length > 0) {
    console.error(
      `stale file icon output: ${stale.map((key) => path.relative(root, outputs[key])).join(', ')}; run bun run icons:generate`,
    )
    process.exit(1)
  }
  process.exit(0)
}

for (const key of Object.keys(files) as (keyof typeof files)[])
  writeFileSync(outputs[key], files[key])
console.log(
  `${glyphs.size} glyphs, ${Object.keys(rules).length} rules, ${maps.fileNames.size} file names, ${maps.extensions.size} extensions`,
)

/** Runs the repo's formatter over an output, so `format:check` and `--check` agree. */
function formatted(file: string, source: string) {
  const result = Bun.spawnSync(
    [path.join(root, 'node_modules', '.bin', 'oxfmt'), `--stdin-filepath=${file}`],
    { cwd: root, stdin: Buffer.from(source), stdout: 'pipe', stderr: 'pipe' },
  )
  if (result.exitCode !== 0)
    throw createScriptError(
      `oxfmt failed on ${path.relative(root, file)}: ${result.stderr.toString()}`,
    )
  return result.stdout.toString()
}

function compareNames(left: string, right: string) {
  return left < right ? -1 : left > right ? 1 : 0
}

function readGlyph(name: string) {
  const svg = readFileSync(path.join(pack, 'svgs', `${name}.svg`), 'utf8')
  const open = /<svg\b[^>]*>/u.exec(svg)
  const viewBox = open ? /viewBox="([^"]+)"/u.exec(open[0])?.[1] : undefined
  const close = svg.lastIndexOf('</svg>')
  if (!open || !viewBox || close < 0)
    throw createScriptError(`${name}.svg has no <svg viewBox> element`)

  const inner = svg.slice(open.index + open[0].length, close).trim()
  return { viewBox, paths: backLayers(namespacedIds(inner, name)) }
}

/** Ids are document-global once a glyph is inlined or in a sprite, so each carries its glyph. */
function namespacedIds(inner: string, name: string) {
  const ids = [...inner.matchAll(/\bid="([^"]+)"/gu)].map((match) => match[1]!)
  let result = inner
  for (const id of ids) {
    const next = `${GRADIENT_PREFIX}${name}-${id}`
    result = result
      .replaceAll(`id="${id}"`, `id="${next}"`)
      .replaceAll(`url(#${id})`, `url(#${next})`)
  }
  return result
}

/**
 * A Catppuccin icon with each of its colours replaced by our hue token, so it follows light and dark.
 * Presentation attributes cannot take `var()`, so colours move into a `style` attribute.
 */
function catppuccinGlyph(icon: string) {
  const source = catppuccin.icons[icon]
  if (!source) throw createScriptError(`@iconify-json/catppuccin has no ${icon} icon`)
  const paths = source.body.replace(
    /<([a-z]+)\b([^>]*?)(\/?)>/gu,
    (_tag, name: string, attributes: string, close: string) => {
      const styles: string[] = []
      const rest = attributes.replace(
        /\s(fill|stroke)="(#[0-9a-fA-F]{6})"/gu,
        (_attribute, property: string, hex: string) => {
          const hue = CATPPUCCIN_HUES[hex.toLowerCase()]
          if (!hue)
            throw createScriptError(`${icon} uses ${hex}, which CATPPUCCIN_HUES does not map`)
          styles.push(`${property}:var(--file-icon-${hue})`)
          return ''
        },
      )
      const style = styles.length > 0 ? ` style="${styles.join(';')}"` : ''
      return `<${name}${rest}${style}${close}>`
    },
  )
  return { viewBox: '0 0 16 16', paths: namespacedIds(paths, `${CATPPUCCIN_PREFIX}${icon}`) }
}

/** A `bg` layer paints `--file-icon-back` when a rule sets one, and the glyph colour otherwise. */
function backLayers(inner: string) {
  return inner.replace(/<path\b([^>]*)\bclass="bg"([^>]*)>/gu, (tag) =>
    tag.replace('fill="currentColor"', 'style="fill:var(--file-icon-back,currentColor)"'),
  )
}

/** Every pack SVG becomes a rule; ours set its hue and names, the pack's maps fill the gaps. */
function resolvedRules() {
  const result: Record<string, Required<Pick<IconRule, 'hue'>> & IconRule & { glyph: string }> = {}
  for (const name of packGlyphNames) result[name] = { glyph: name, hue: 'gray' }
  for (const [name, rule] of Object.entries(RULES)) {
    const glyph = rule.glyph ?? name
    if (!glyphs.has(glyph))
      throw createScriptError(`rule ${name} draws ${glyph}, which the pack lacks`)
    result[name] = { ...rule, glyph }
  }
  for (const [name, rule] of Object.entries(CATPPUCCIN_RULES)) {
    if (name in result) throw createScriptError(`Catppuccin rule ${name} shadows a pack rule`)
    result[name] = { ...rule, glyph: `${CATPPUCCIN_PREFIX}${rule.icon}` }
  }
  for (const rule of Object.values(result)) {
    for (const hue of [rule.hue, rule.backHue]) {
      if (hue && !HUES.includes(hue)) throw createScriptError(`unknown hue ${hue}`)
    }
  }
  return result
}

function ruleMaps(resolved: typeof rules) {
  const fileNames = new Map<string, string>()
  const extensions = new Map<string, string>()
  const claim = (map: Map<string, string>, key: string, rule: string) => {
    const normalized = key.trim().toLocaleLowerCase()
    if (!map.has(normalized)) map.set(normalized, rule)
  }
  for (const [name, rule] of [...Object.entries(RULES), ...Object.entries(CATPPUCCIN_RULES)]) {
    for (const fileName of rule.fileNames ?? []) claim(fileNames, fileName, name)
    for (const extension of rule.extensions ?? []) claim(extensions, extension, name)
  }
  for (const entry of tiers.flat()) {
    const name = PACK_NAME_ALIASES[entry.name] ?? entry.name
    if (!(name in resolved)) continue
    for (const fileName of entry.fileNames ?? []) claim(fileNames, fileName, name)
    for (const extension of entry.fileExtensions ?? []) {
      if (PACK_EXTENSIONS_THAT_ARE_FILE_NAMES.has(extension)) claim(fileNames, extension, name)
      else claim(extensions, `.${extension}`, name)
    }
  }
  return { fileNames: sortedMap(fileNames), extensions: sortedMap(extensions) }
}

function sortedMap(map: Map<string, string>) {
  return new Map([...map].toSorted(([left], [right]) => compareNames(left, right)))
}

function hueClass(rule: IconRule) {
  const front = `text-file-icon-${rule.hue}`
  if (!rule.backHue) return front
  return `${front} [--file-icon-back:var(--color-file-icon-${rule.backHue})]`
}

function hueValues(hue: IconHue): readonly [string, string] {
  const local = LOCAL_HUES[hue]
  if (local) return local
  const packHue = palette[hue as keyof typeof palette]
  if (!packHue) throw createScriptError(`the pack palette has no ${hue}`)
  return [(LIGHT_OVERRIDES[hue] ?? packHue[600]).toLowerCase(), packHue[400].toLowerCase()]
}

function glyphFile() {
  const entries = glyphNames.map((name) => {
    const glyph = glyphs.get(name)!
    return `  ${key(name)}: {\n    viewBox: '${glyph.viewBox}',\n    paths: \`${glyph.paths}\`,\n  },`
  })
  return `// ${HEADER}

export const VSCODE_ICON_GLYPHS = {
${entries.join('\n')}
} as const

export type FileIconGlyph = keyof typeof VSCODE_ICON_GLYPHS
`
}

function rulesFile() {
  const ruleLines = Object.entries(rules)
    .toSorted(([left], [right]) => compareNames(left, right))
    .map(
      ([name, rule]) =>
        `  ${key(name)}: { glyph: '${rule.glyph}', hue: '${rule.hue}', className: '${hueClass(rule)}' },`,
    )
  const mapLines = (map: Map<string, string>) =>
    [...map].map(([name, rule]) => `  ${key(name)}: '${rule}',`).join('\n')
  return `// ${HEADER}
import type { FileIconGlyph } from '@/lib/vscode-icon-glyphs'

type FileIconHue = ${HUES.map((hue) => `'${hue}'`).join(' | ')}

type FileIconRule = {
  readonly glyph: FileIconGlyph
  readonly hue: FileIconHue
  /** Literal Tailwind classes, so the scanner sees every one. */
  readonly className: string
}

export const FILE_ICON_RULES = {
${ruleLines.join('\n')}
} as const satisfies Record<string, FileIconRule>

export type FileIconRuleName = keyof typeof FILE_ICON_RULES

export const FILE_ICON_FILE_NAMES: Readonly<Record<string, FileIconRuleName>> = {
${mapLines(maps.fileNames)}
}

export const FILE_ICON_EXTENSIONS: Readonly<Record<string, FileIconRuleName>> = {
${mapLines(maps.extensions)}
}
`
}

function cssFile() {
  const values = HUES.map((hue) => [hue, hueValues(hue)] as const)
  const light = values.map(([hue, [value]]) => `  --file-icon-${hue}: ${value};`)
  const dark = values.map(([hue, [, value]]) => `  --file-icon-${hue}: ${value};`)
  const theme = HUES.map((hue) => `  --color-file-icon-${hue}: var(--file-icon-${hue});`)
  return `/* ${HEADER} */
:root {
${light.join('\n')}
  --file-icon-neutral: ${palette.gray![800]!.toLowerCase()};
}

.dark {
${dark.join('\n')}
  --file-icon-neutral: ${palette.gray![400].toLowerCase()};
}

@theme inline {
${theme.join('\n')}
  --color-file-icon-neutral: var(--file-icon-neutral);
}
`
}

function key(name: string) {
  return /^[A-Za-z_$][\w$]*$/u.test(name) ? name : `'${name}'`
}
