// Comparison data follows VS Code's MIT-licensed strings.ts, generated by hediet/vscode-unicode-data.
import confusables from '@/features/editor/utils/unicode-confusables.json'

const comparisons: Readonly<Record<string, number>> = confusables

export function unicodeCharacterMessage(
  codePoint: number,
  kind: 'ambiguous' | 'invisible',
): string {
  const code = formatCodePoint(codePoint)
  if (kind === 'invisible') return `The character ${code} is invisible.`
  const comparison = comparisons[String(codePoint)]
  if (comparison === undefined) return `The character ${code} resembles another character.`
  return `The character ${code} ${renderCharacter(codePoint)} could be confused with ${formatCodePoint(comparison)} ${renderCharacter(comparison)}, which is more common in source code.`
}

function formatCodePoint(codePoint: number): string {
  return `\`U+${codePoint.toString(16).toUpperCase().padStart(4, '0')}\``
}

function renderCharacter(codePoint: number): string {
  if (codePoint === 96) return '`` ` ``'
  return `\`${String.fromCodePoint(codePoint)}\``
}
