import type { Binding } from '@fregat/hotkeys'

export const applicationBindings: readonly (Binding & { readonly firesWhileTyping: boolean })[] = [
  {
    keys: 'Mod+S',
    command: 'chat.stashPrompt',
    context: 'Chat > Composer',
    source: 'base',
    firesWhileTyping: true,
  },
  {
    keys: 'Enter',
    command: 'chat.sendMessage',
    context: 'Chat > Composer',
    source: 'base',
    firesWhileTyping: true,
  },
  {
    keys: 'Mod+Enter',
    command: 'chat.sendMessage',
    context: 'Chat > Composer',
    source: 'base',
    firesWhileTyping: true,
  },
  {
    keys: 'Mod+Shift+Enter',
    command: 'chat.sendMessage',
    context: 'Chat > Composer',
    source: 'base',
    firesWhileTyping: true,
  },
  {
    keys: 'Mod+Shift+V',
    command: 'chat.pasteAsText',
    context: 'Chat > Composer',
    source: 'base',
    firesWhileTyping: true,
    preventDefault: false,
    stopPropagation: false,
  },
  {
    keys: '1',
    command: 'question.select1',
    context: 'Chat > Question',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: '2',
    command: 'question.select2',
    context: 'Chat > Question',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: '3',
    command: 'question.select3',
    context: 'Chat > Question',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: '4',
    command: 'question.select4',
    context: 'Chat > Question',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: '5',
    command: 'question.select5',
    context: 'Chat > Question',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: '6',
    command: 'question.select6',
    context: 'Chat > Question',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: '7',
    command: 'question.select7',
    context: 'Chat > Question',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: '8',
    command: 'question.select8',
    context: 'Chat > Question',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: '9',
    command: 'question.select9',
    context: 'Chat > Question',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: 'Mod+Enter',
    command: 'git.commit',
    context: 'Sidebar > Git > GitCommit',
    source: 'base',
    firesWhileTyping: true,
  },
  {
    keys: 'Mod+A',
    command: 'fileTree.selectAll',
    context: 'Sidebar > FileTree > TreeSelection',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: 'Mod+Space',
    command: 'fileTree.toggleMark',
    context: 'Sidebar > FileTree > TreeSelection',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: 'F2',
    command: 'fileTree.rename',
    context: 'Sidebar > FileTree > TreeSelection',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: 'Mod+[',
    command: 'filePicker.navigateBack',
    context: 'Dialog > FilePicker',
    source: 'base',
    firesWhileTyping: true,
  },
  {
    keys: 'Mod+]',
    command: 'filePicker.navigateForward',
    context: 'Dialog > FilePicker',
    source: 'base',
    firesWhileTyping: true,
  },
  {
    keys: 'Mod+ArrowDown',
    command: 'filePicker.openSelected',
    context: 'Dialog > FilePicker',
    source: 'base',
    firesWhileTyping: true,
  },
  {
    keys: 'Mod+Shift+G',
    command: 'filePicker.goToFolder',
    context: 'Dialog > FilePicker',
    source: 'base',
    firesWhileTyping: true,
  },
  {
    keys: 'Mod+Shift+Period',
    command: 'filePicker.toggleHidden',
    context: 'Dialog > FilePicker',
    source: 'base',
    firesWhileTyping: true,
  },
  {
    keys: 'Mod+ArrowUp',
    command: 'filePicker.goUp',
    context: 'Dialog > FilePicker',
    source: 'base',
    firesWhileTyping: true,
  },
  {
    keys: 'Escape',
    command: 'themeStudio.close',
    context: 'Settings > ThemeStudio',
    source: 'base',
    firesWhileTyping: true,
  },
  {
    keys: '\\',
    command: 'themeStudio.toggleMode',
    context: 'Settings > ThemeStudio',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: 'Enter',
    command: 'themeStudio.apply',
    context: 'Settings > ThemeStudio',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: 'F2',
    command: 'terminal.rename',
    context: 'TerminalList',
    source: 'base',
    firesWhileTyping: false,
  },
  {
    keys: 'Delete',
    command: 'terminal.close',
    context: 'TerminalList',
    source: 'base',
    firesWhileTyping: false,
  },
]
