import type { Binding } from '@fregat/hotkeys'

export type RuntimeRow = readonly [
  index: number,
  platform: string,
  keys: string,
  command: string | null,
  context: string,
  upstreamCommand: string,
  args?: Binding['args'],
]

export const presetRuntimeRows: readonly RuntimeRow[] = [
  [23, 'linux', 'Ctrl+O', 'workspace.openFilePicker', 'Workspace', 'workspace::OpenFiles'],
  [41, 'linux', 'Shift+Backspace', 'editor.deleteBackward', 'Editor', 'editor::Backspace'],
  [42, 'linux', 'Backspace', 'editor.deleteBackward', 'Editor', 'editor::Backspace'],
  [43, 'linux', 'Delete', 'editor.deleteForward', 'Editor', 'editor::Delete'],
  [44, 'linux', 'Tab', 'editor.indentSelection', 'Editor', 'editor::Tab'],
  [45, 'linux', 'Shift+Tab', 'editor.outdentSelection', 'Editor', 'editor::Backtab'],
  [
    48,
    'linux',
    'Ctrl+Backspace',
    'editor.deleteWordLeft',
    'Editor',
    '["editor::DeleteToPreviousWordStart",{"ignore_newlines":false,"ignore_brackets":false}]',
  ],
  [
    49,
    'linux',
    'Ctrl+Delete',
    'editor.deleteWordRight',
    'Editor',
    '["editor::DeleteToNextWordEnd",{"ignore_newlines":false,"ignore_brackets":false}]',
  ],
  [59, 'linux', 'UNDO', 'editor.undo', 'Editor', 'editor::Undo'],
  [60, 'linux', 'Ctrl+Z', 'editor.undo', 'Editor', 'editor::Undo'],
  [62, 'linux', 'Ctrl+Y', 'editor.redo', 'Editor', 'editor::Redo'],
  [63, 'linux', 'Ctrl+Shift+Z', 'editor.redo', 'Editor', 'editor::Redo'],
  [64, 'linux', 'ArrowUp', 'editor.cursorUp', 'Editor', 'editor::MoveUp'],
  [67, 'linux', 'PageUp', 'editor.cursorPageUp', 'Editor', 'editor::MovePageUp'],
  [69, 'linux', 'Shift+PageUp', 'editor.selectPageUp', 'Editor', 'editor::SelectPageUp'],
  [
    70,
    'linux',
    'Home',
    'editor.cursorLineStart',
    'Editor',
    '["editor::MoveToBeginningOfLine",{"stop_at_soft_wraps":true,"stop_at_indent":true}]',
  ],
  [71, 'linux', 'ArrowDown', 'editor.cursorDown', 'Editor', 'editor::MoveDown'],
  [72, 'linux', 'PageDown', 'editor.cursorPageDown', 'Editor', 'editor::MovePageDown'],
  [74, 'linux', 'Shift+PageDown', 'editor.selectPageDown', 'Editor', 'editor::SelectPageDown'],
  [
    75,
    'linux',
    'End',
    'editor.cursorLineEnd',
    'Editor',
    '["editor::MoveToEndOfLine",{"stop_at_soft_wraps":true}]',
  ],
  [76, 'linux', 'ArrowLeft', 'editor.cursorLeft', 'Editor', 'editor::MoveLeft'],
  [77, 'linux', 'ArrowRight', 'editor.cursorRight', 'Editor', 'editor::MoveRight'],
  [
    78,
    'linux',
    'Ctrl+ArrowLeft',
    'editor.cursorWordLeft',
    'Editor',
    'editor::MoveToPreviousWordStart',
  ],
  [79, 'linux', 'Ctrl+ArrowRight', 'editor.cursorWordRight', 'Editor', 'editor::MoveToNextWordEnd'],
  [80, 'linux', 'Ctrl+Home', 'editor.cursorDocumentStart', 'Editor', 'editor::MoveToBeginning'],
  [81, 'linux', 'Ctrl+End', 'editor.cursorDocumentEnd', 'Editor', 'editor::MoveToEnd'],
  [82, 'linux', 'Shift+ArrowUp', 'editor.selectUp', 'Editor', 'editor::SelectUp'],
  [83, 'linux', 'Shift+ArrowDown', 'editor.selectDown', 'Editor', 'editor::SelectDown'],
  [84, 'linux', 'Shift+ArrowLeft', 'editor.selectLeft', 'Editor', 'editor::SelectLeft'],
  [85, 'linux', 'Shift+ArrowRight', 'editor.selectRight', 'Editor', 'editor::SelectRight'],
  [
    86,
    'linux',
    'Ctrl+Shift+ArrowLeft',
    'editor.selectWordLeft',
    'Editor',
    'editor::SelectToPreviousWordStart',
  ],
  [
    87,
    'linux',
    'Ctrl+Shift+ArrowRight',
    'editor.selectWordRight',
    'Editor',
    'editor::SelectToNextWordEnd',
  ],
  [
    88,
    'linux',
    'Ctrl+Shift+Home',
    'editor.selectDocumentStart',
    'Editor',
    'editor::SelectToBeginning',
  ],
  [89, 'linux', 'Ctrl+Shift+End', 'editor.selectDocumentEnd', 'Editor', 'editor::SelectToEnd'],
  [90, 'linux', 'Ctrl+A', 'editor.selectAll', 'Editor', 'editor::SelectAll'],
  [92, 'linux', 'Ctrl+Shift+I', 'editor.action.formatDocument', 'Editor', 'editor::Format'],
  [
    94,
    'linux',
    'Shift+Home',
    'editor.selectLineStart',
    'Editor',
    '["editor::SelectToBeginningOfLine",{"stop_at_soft_wraps":true,"stop_at_indent":true}]',
  ],
  [
    95,
    'linux',
    'Shift+End',
    'editor.selectLineEnd',
    'Editor',
    '["editor::SelectToEndOfLine",{"stop_at_soft_wraps":true}]',
  ],
  [
    111,
    'linux',
    'Ctrl+Enter',
    'editor.action.insertLineAfter',
    'Editor && mode == full',
    'editor::NewlineBelow',
  ],
  [
    112,
    'linux',
    'Ctrl+Shift+Enter',
    'editor.action.insertLineBefore',
    'Editor && mode == full',
    'editor::NewlineAbove',
  ],
  [
    113,
    'linux',
    'Ctrl+K Ctrl+Z',
    'editor.action.toggleWordWrap',
    'Editor && mode == full',
    'editor::ToggleSoftWrap',
  ],
  [
    114,
    'linux',
    'Ctrl+K Z',
    'editor.action.toggleWordWrap',
    'Editor && mode == full',
    'editor::ToggleSoftWrap',
  ],
  [115, 'linux', 'FIND', 'editor.find', 'Editor && mode == full', 'buffer_search::Deploy'],
  [116, 'linux', 'Ctrl+F', 'editor.find', 'Editor && mode == full', 'buffer_search::Deploy'],
  [
    117,
    'linux',
    'Ctrl+H',
    'editor.findReplace',
    'Editor && mode == full',
    'buffer_search::DeployReplace',
  ],
  [
    118,
    'linux',
    'Ctrl+>',
    'workspace.addSelectionToChat',
    'Editor && mode == full',
    'agent::AddSelectionToThread',
  ],
  [
    129,
    'linux',
    'Ctrl+Shift+Enter',
    'editor.action.insertLineAfter',
    'Editor && mode == single_line',
    'editor::NewlineBelow',
  ],
  [150, 'linux', 'Ctrl+N', 'workspace.newChat', 'Chat', 'agent::NewThread'],
  [151, 'linux', 'Ctrl+Alt+C', 'workspace.showSettings', 'Chat', 'agent::OpenSettings'],
  [154, 'linux', 'Ctrl+Shift+E', 'workspace.focusFileTree', 'Chat', 'project_panel::ToggleFocus'],
  [161, 'linux', 'Ctrl+N', 'workspace.newChat', 'Chat', 'agent::NewThread'],
  [162, 'linux', 'Ctrl+-', 'workspace.navigateBack', 'Chat', 'pane::GoBack'],
  [171, 'linux', 'Ctrl+>', 'workspace.addSelectionToChat', 'Chat', 'agent::AddSelectionToThread'],
  [
    241,
    'linux',
    'Enter',
    'chat.sendMessage',
    'Chat > Editor && !use_modifier_to_send',
    'agent::Chat',
  ],
  [249, 'linux', 'Escape', 'editor.closeFind', 'Editor > FindWidget', 'buffer_search::Dismiss'],
  [
    250,
    'linux',
    'Tab',
    'workspace.focusEditor',
    'Editor > FindWidget',
    'buffer_search::FocusEditor',
  ],
  [251, 'linux', 'Enter', 'editor.findNext', 'Editor > FindWidget', 'search::SelectNextMatch'],
  [
    252,
    'linux',
    'Shift+Enter',
    'editor.findPrevious',
    'Editor > FindWidget',
    'search::SelectPreviousMatch',
  ],
  [
    254,
    'linux',
    'Alt+Enter',
    'editor.selectAllMatches',
    'Editor > FindWidget',
    'search::SelectAllMatches',
  ],
  [
    258,
    'linux',
    'Ctrl+L',
    'editor.toggleFindInSelection',
    'Editor > FindWidget',
    'search::ToggleSelection',
  ],
  [260, 'linux', 'Enter', 'editor.replaceOne', 'Editor > ReplaceInput', 'search::ReplaceNext'],
  [261, 'linux', 'Ctrl+Enter', 'editor.replaceAll', 'Editor > ReplaceInput', 'search::ReplaceAll'],
  [
    263,
    'linux',
    'Shift+Enter',
    'editor.findPrevious',
    'Editor > (FindWidget && !ReplaceInput)',
    'search::SelectPreviousMatch',
  ],
  [
    284,
    'linux',
    'Alt+1',
    'workspace.selectItem1',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",0]',
  ],
  [
    285,
    'linux',
    'Alt+2',
    'workspace.selectItem2',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",1]',
  ],
  [
    286,
    'linux',
    'Alt+3',
    'workspace.selectItem3',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",2]',
  ],
  [
    287,
    'linux',
    'Alt+4',
    'workspace.selectItem4',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",3]',
  ],
  [
    288,
    'linux',
    'Alt+5',
    'workspace.selectItem5',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",4]',
  ],
  [
    289,
    'linux',
    'Alt+6',
    'workspace.selectItem6',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",5]',
  ],
  [
    290,
    'linux',
    'Alt+7',
    'workspace.selectItem7',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",6]',
  ],
  [
    291,
    'linux',
    'Alt+8',
    'workspace.selectItem8',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",7]',
  ],
  [
    293,
    'linux',
    'Alt+0',
    'workspace.selectItem9',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::ActivateLastItem',
  ],
  [
    294,
    'linux',
    'Ctrl+PageUp',
    'workspace.previousItem',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::ActivatePreviousItem',
  ],
  [
    295,
    'linux',
    'Ctrl+PageDown',
    'workspace.nextItem',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::ActivateNextItem',
  ],
  [
    298,
    'linux',
    'Ctrl+F4',
    'workspace.closeCurrentTab',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::CloseActiveItem",{"close_pinned":false}]',
  ],
  [
    299,
    'linux',
    'Ctrl+W',
    'workspace.closeCurrentTab',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::CloseActiveItem",{"close_pinned":false}]',
  ],
  [
    308,
    'linux',
    'Ctrl+Alt+-',
    'workspace.navigateBack',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::GoBack',
  ],
  [
    310,
    'linux',
    'Ctrl+Alt+_',
    'workspace.navigateForward',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::GoForward',
  ],
  [
    311,
    'linux',
    'Ctrl+Alt+G',
    'editor.findNext',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::SelectNextMatch',
  ],
  [
    312,
    'linux',
    'F3',
    'editor.findNext',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::SelectNextMatch',
  ],
  [
    313,
    'linux',
    'Ctrl+Alt+Shift+G',
    'editor.findPrevious',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::SelectPreviousMatch',
  ],
  [
    314,
    'linux',
    'Shift+F3',
    'editor.findPrevious',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::SelectPreviousMatch',
  ],
  [
    318,
    'linux',
    'Ctrl+Alt+Shift+L',
    'editor.toggleFindInSelection',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::ToggleSelection',
  ],
  [
    319,
    'linux',
    'Alt+Enter',
    'editor.selectAllMatches',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::SelectAllMatches',
  ],
  [
    320,
    'linux',
    'Alt+C',
    'editor.toggleFindCaseSensitive',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::ToggleCaseSensitive',
  ],
  [
    321,
    'linux',
    'Alt+W',
    'editor.toggleFindWholeWord',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::ToggleWholeWord',
  ],
  [
    325,
    'linux',
    'Ctrl+Alt+Shift+R',
    'editor.toggleFindRegex',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::ToggleRegex',
  ],
  [
    326,
    'linux',
    'Ctrl+Alt+Shift+X',
    'editor.toggleFindRegex',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::ToggleRegex',
  ],
  [
    327,
    'linux',
    'Alt+R',
    'editor.toggleFindRegex',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::ToggleRegex',
  ],
  [329, 'linux', 'Ctrl+[', 'editor.action.outdentLines', 'Editor', 'editor::Outdent'],
  [330, 'linux', 'Ctrl+]', 'editor.action.indentLines', 'Editor', 'editor::Indent'],
  [
    331,
    'linux',
    'Shift+Alt+ArrowUp',
    'editor.action.insertCursorAbove',
    'Editor',
    '["editor::AddSelectionAbove",{"skip_soft_wrap":true}]',
  ],
  [
    332,
    'linux',
    'Shift+Alt+ArrowDown',
    'editor.action.insertCursorBelow',
    'Editor',
    '["editor::AddSelectionBelow",{"skip_soft_wrap":true}]',
  ],
  [333, 'linux', 'Ctrl+Shift+K', 'editor.action.deleteLines', 'Editor', 'editor::DeleteLine'],
  [334, 'linux', 'Alt+ArrowUp', 'editor.action.moveLinesUpAction', 'Editor', 'editor::MoveLineUp'],
  [
    335,
    'linux',
    'Alt+ArrowDown',
    'editor.action.moveLinesDownAction',
    'Editor',
    'editor::MoveLineDown',
  ],
  [
    336,
    'linux',
    'Ctrl+Alt+Shift+ArrowUp',
    'editor.action.copyLinesUpAction',
    'Editor',
    'editor::DuplicateLineUp',
  ],
  [
    337,
    'linux',
    'Ctrl+Alt+Shift+ArrowDown',
    'editor.action.copyLinesDownAction',
    'Editor',
    'editor::DuplicateLineDown',
  ],
  [
    338,
    'linux',
    'Alt+Shift+ArrowRight',
    'editor.action.smartSelect.expand',
    'Editor',
    'editor::SelectLargerSyntaxNode',
  ],
  [
    339,
    'linux',
    'Alt+Shift+ArrowLeft',
    'editor.action.smartSelect.shrink',
    'Editor',
    'editor::SelectSmallerSyntaxNode',
  ],
  [
    340,
    'linux',
    'Ctrl+Shift+L',
    'editor.action.selectHighlights',
    'Editor',
    'editor::SelectAllMatches',
  ],
  [341, 'linux', 'Ctrl+F2', 'editor.action.selectHighlights', 'Editor', 'editor::SelectAllMatches'],
  [
    342,
    'linux',
    'Ctrl+D',
    'editor.addNextOccurrence',
    'Editor',
    '["editor::SelectNext",{"replace_newest":false}]',
  ],
  [
    343,
    'linux',
    'Ctrl+Shift+ArrowDown',
    'editor.addNextOccurrence',
    'Editor',
    '["editor::SelectNext",{"replace_newest":false}]',
  ],
  [
    345,
    'linux',
    'Ctrl+K Ctrl+D',
    'editor.action.moveSelectionToNextFindMatch',
    'Editor',
    '["editor::SelectNext",{"replace_newest":true}]',
  ],
  [347, 'linux', 'Ctrl+K Ctrl+I', 'editor.action.showHover', 'Editor', 'editor::Hover'],
  [
    349,
    'linux',
    'Ctrl+/',
    'editor.action.commentLine',
    'Editor',
    '["editor::ToggleComments",{"advance_downwards":false,"comment_empty_lines":true}]',
  ],
  [
    350,
    'linux',
    'Ctrl+K Ctrl+C',
    'editor.action.commentLine',
    'Editor',
    '["editor::ToggleComments",{"advance_downwards":false,"comment_empty_lines":true}]',
  ],
  [
    351,
    'linux',
    'Ctrl+K Ctrl+/',
    'editor.action.blockComment',
    'Editor',
    'editor::ToggleBlockComments',
  ],
  [
    352,
    'linux',
    'Shift+Alt+A',
    'editor.action.blockComment',
    'Editor',
    'editor::ToggleBlockComments',
  ],
  [
    353,
    'linux',
    'F8',
    'editor.action.marker.next',
    'Editor',
    '["editor::GoToDiagnostic",{"severity":{"min":"hint","max":"error"}}]',
  ],
  [
    354,
    'linux',
    'Shift+F8',
    'editor.action.marker.prev',
    'Editor',
    '["editor::GoToPreviousDiagnostic",{"severity":{"min":"hint","max":"error"}}]',
  ],
  [355, 'linux', 'F2', 'editor.action.rename', 'Editor', 'editor::Rename'],
  [356, 'linux', 'F12', 'editor.action.goToDefinition', 'Editor', 'editor::GoToDefinition'],
  [
    357,
    'linux',
    'Alt+F12',
    'editor.action.revealDefinitionAside',
    'Editor',
    'editor::GoToDefinitionSplit',
  ],
  [
    358,
    'linux',
    'Ctrl+Shift+F10',
    'editor.action.revealDefinitionAside',
    'Editor',
    'editor::GoToDefinitionSplit',
  ],
  [
    359,
    'linux',
    'Ctrl+F12',
    'editor.action.goToTypeDefinition',
    'Editor',
    'editor::GoToTypeDefinition',
  ],
  [
    360,
    'linux',
    'Shift+F12',
    'editor.action.goToImplementation',
    'Editor',
    'editor::GoToImplementation',
  ],
  [
    362,
    'linux',
    'Alt+Shift+F12',
    'editor.action.goToReferences',
    'Editor',
    'editor::FindAllReferences',
  ],
  [
    364,
    'linux',
    'Ctrl+M',
    'editor.action.jumpToBracket',
    'Editor',
    'editor::MoveToEnclosingBracket',
  ],
  [
    365,
    'linux',
    'Ctrl+|',
    'editor.action.jumpToBracket',
    'Editor',
    'editor::MoveToEnclosingBracket',
  ],
  [366, 'linux', 'Ctrl+{', 'editor.fold', 'Editor', 'editor::Fold'],
  [367, 'linux', 'Ctrl+}', 'editor.unfold', 'Editor', 'editor::UnfoldLines'],
  [369, 'linux', 'Ctrl+K Ctrl+[', 'editor.foldRecursively', 'Editor', 'editor::FoldRecursive'],
  [370, 'linux', 'Ctrl+K Ctrl+]', 'editor.unfoldRecursively', 'Editor', 'editor::UnfoldRecursive'],
  [371, 'linux', 'Ctrl+K Ctrl+1', 'editor.foldLevel1', 'Editor', 'editor::FoldAtLevel_1'],
  [372, 'linux', 'Ctrl+K Ctrl+2', 'editor.foldLevel2', 'Editor', 'editor::FoldAtLevel_2'],
  [373, 'linux', 'Ctrl+K Ctrl+3', 'editor.foldLevel3', 'Editor', 'editor::FoldAtLevel_3'],
  [374, 'linux', 'Ctrl+K Ctrl+4', 'editor.foldLevel4', 'Editor', 'editor::FoldAtLevel_4'],
  [375, 'linux', 'Ctrl+K Ctrl+5', 'editor.foldLevel5', 'Editor', 'editor::FoldAtLevel_5'],
  [376, 'linux', 'Ctrl+K Ctrl+6', 'editor.foldLevel6', 'Editor', 'editor::FoldAtLevel_6'],
  [377, 'linux', 'Ctrl+K Ctrl+7', 'editor.foldLevel7', 'Editor', 'editor::FoldAtLevel_7'],
  [380, 'linux', 'Ctrl+K Ctrl+0', 'editor.foldAll', 'Editor', 'editor::FoldAll'],
  [381, 'linux', 'Ctrl+K Ctrl+J', 'editor.unfoldAll', 'Editor', 'editor::UnfoldAll'],
  [382, 'linux', 'Ctrl+Space', 'editor.action.triggerSuggest', 'Editor', 'editor::ShowCompletions'],
  [387, 'linux', 'Ctrl+\\', 'workspace.splitEditorRight', 'Editor', 'pane::SplitRight'],
  [
    397,
    'linux',
    'Ctrl+Shift+O',
    'workspace.gotoSymbol',
    'Editor && mode == full',
    'outline::Toggle',
  ],
  [398, 'linux', 'Ctrl+G', 'workspace.goToLine', 'Editor && mode == full', 'go_to_line::Toggle'],
  [412, 'linux', 'Ctrl+~', 'workspace.newTerminal', 'Workspace', 'workspace::NewTerminal'],
  [414, 'linux', 'Ctrl+S', 'workspace.saveFile', 'Workspace', 'workspace::Save'],
  [422, 'linux', 'Ctrl+`', 'workspace.revealTerminal', 'Workspace', 'terminal_panel::Toggle'],
  [
    424,
    'linux',
    'Alt+1',
    'workspace.focusFirstEditorGroup',
    'Workspace',
    '["workspace::ActivatePane",0]',
  ],
  [
    425,
    'linux',
    'Alt+2',
    'workspace.focusSecondEditorGroup',
    'Workspace',
    '["workspace::ActivatePane",1]',
  ],
  [
    426,
    'linux',
    'Alt+3',
    'workspace.focusThirdEditorGroup',
    'Workspace',
    '["workspace::ActivatePane",2]',
  ],
  [
    434,
    'linux',
    'Ctrl+B',
    'workspace.toggleSidebarVisibility',
    'Workspace',
    'workspace::ToggleLeftDock',
  ],
  [435, 'linux', 'Ctrl+J', 'workspace.togglePanel', 'Workspace', 'workspace::ToggleBottomDock'],
  [
    436,
    'linux',
    'Ctrl+Alt+J',
    'workspace.toggleSessionRail',
    'Workspace',
    'multi_workspace::ToggleWorkspaceSidebar',
  ],
  [
    448,
    'linux',
    'Ctrl+Shift+T',
    'workspace.reopenClosedEditor',
    'Workspace',
    'pane::ReopenClosedItem',
  ],
  [
    451,
    'linux',
    'Ctrl+K Ctrl+T',
    'workspace.selectThemeBundle',
    'Workspace',
    'theme_selector::Toggle',
  ],
  [455, 'linux', 'Ctrl+P', 'workspace.showQuickAccess', 'Workspace', 'file_finder::Toggle'],
  [458, 'linux', 'Ctrl+E', 'workspace.showQuickAccess', 'Workspace', 'file_finder::Toggle'],
  [459, 'linux', 'F1', 'workspace.showCommandPalette', 'Workspace', 'command_palette::Toggle'],
  [
    460,
    'linux',
    'Ctrl+Shift+P',
    'workspace.showCommandPalette',
    'Workspace',
    'command_palette::Toggle',
  ],
  [
    462,
    'linux',
    'Ctrl+Shift+E',
    'workspace.focusFileTree',
    'Workspace',
    'project_panel::ToggleFocus',
  ],
  [464, 'linux', 'Ctrl+Shift+G', 'workspace.focusGit', 'Workspace', 'git_panel::ToggleFocus'],
  [466, 'linux', 'Ctrl+?', 'workspace.revealChat', 'Workspace', 'agent::ToggleFocus'],
  [468, 'linux', 'Ctrl+Alt+S', 'workspace.saveAllFiles', 'Workspace', 'workspace::SaveAll'],
  [
    488,
    'linux',
    'Ctrl+F4',
    'workspace.closeCurrentTab',
    'Workspace',
    '["pane::CloseActiveItem",{"close_pinned":false}]',
  ],
  [
    489,
    'linux',
    'Ctrl+W',
    'workspace.closeCurrentTab',
    'Workspace',
    '["pane::CloseActiveItem",{"close_pinned":false}]',
  ],
  [515, 'linux', 'Ctrl+U', 'editor.cursorUndo', 'Editor', 'editor::UndoSelection'],
  [516, 'linux', 'Ctrl+Shift+U', 'editor.cursorRedo', 'Editor', 'editor::RedoSelection'],
  [517, 'linux', 'Ctrl+Shift+J', 'editor.action.joinLines', 'Editor', 'editor::JoinLines'],
  [
    518,
    'linux',
    'Ctrl+Alt+Backspace',
    'editor.deleteWordPartLeft',
    'Editor',
    'editor::DeleteToPreviousSubwordStart',
  ],
  [
    519,
    'linux',
    'Ctrl+Alt+H',
    'editor.deleteWordPartLeft',
    'Editor',
    'editor::DeleteToPreviousSubwordStart',
  ],
  [
    520,
    'linux',
    'Ctrl+Alt+Delete',
    'editor.deleteWordPartRight',
    'Editor',
    'editor::DeleteToNextSubwordEnd',
  ],
  [
    521,
    'linux',
    'Ctrl+Alt+D',
    'editor.deleteWordPartRight',
    'Editor',
    'editor::DeleteToNextSubwordEnd',
  ],
  [
    522,
    'linux',
    'Ctrl+Alt+ArrowLeft',
    'editor.cursorWordPartLeft',
    'Editor',
    'editor::MoveToPreviousSubwordStart',
  ],
  [
    523,
    'linux',
    'Ctrl+Alt+ArrowRight',
    'editor.cursorWordPartRight',
    'Editor',
    'editor::MoveToNextSubwordEnd',
  ],
  [
    524,
    'linux',
    'Ctrl+Alt+Shift+ArrowLeft',
    'editor.cursorWordPartLeftSelect',
    'Editor',
    'editor::SelectToPreviousSubwordStart',
  ],
  [
    525,
    'linux',
    'Ctrl+Alt+Shift+B',
    'editor.cursorWordPartLeftSelect',
    'Editor',
    'editor::SelectToPreviousSubwordStart',
  ],
  [
    526,
    'linux',
    'Ctrl+Alt+Shift+ArrowRight',
    'editor.cursorWordPartRightSelect',
    'Editor',
    'editor::SelectToNextSubwordEnd',
  ],
  [
    527,
    'linux',
    'Ctrl+Alt+Shift+F',
    'editor.cursorWordPartRightSelect',
    'Editor',
    'editor::SelectToNextSubwordEnd',
  ],
  [
    529,
    'linux',
    'Ctrl+K ArrowDown',
    'workspace.splitEditorDown',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::SplitDown',
  ],
  [
    531,
    'linux',
    'Ctrl+K ArrowRight',
    'workspace.splitEditorRight',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::SplitRight',
  ],
  [
    534,
    'linux',
    'Enter',
    'editor.acceptSelectedSuggestion',
    'Editor && suggestWidgetVisible',
    'editor::ConfirmCompletion',
  ],
  [
    539,
    'linux',
    'Alt+Tab',
    'editor.action.inlineSuggest.commit',
    'Editor && inlineSuggestionVisible',
    'editor::AcceptEditPrediction',
  ],
  [
    540,
    'linux',
    'Alt+L',
    'editor.action.inlineSuggest.commit',
    'Editor && inlineSuggestionVisible',
    'editor::AcceptEditPrediction',
  ],
  [
    541,
    'linux',
    'Alt+K',
    'editor.action.inlineSuggest.acceptNextWord',
    'Editor && inlineSuggestionVisible',
    'editor::AcceptNextWordEditPrediction',
  ],
  [
    545,
    'linux',
    'Ctrl+P',
    'editor.selectPrevSuggestion',
    'Editor && (showing_code_actions || suggestWidgetVisible)',
    'editor::ContextMenuPrevious',
  ],
  [
    546,
    'linux',
    'ArrowUp',
    'editor.selectPrevSuggestion',
    'Editor && (showing_code_actions || suggestWidgetVisible)',
    'editor::ContextMenuPrevious',
  ],
  [
    547,
    'linux',
    'Ctrl+N',
    'editor.selectNextSuggestion',
    'Editor && (showing_code_actions || suggestWidgetVisible)',
    'editor::ContextMenuNext',
  ],
  [
    548,
    'linux',
    'ArrowDown',
    'editor.selectNextSuggestion',
    'Editor && (showing_code_actions || suggestWidgetVisible)',
    'editor::ContextMenuNext',
  ],
  [
    551,
    'linux',
    'ArrowUp',
    'editor.showPrevParameterHint',
    'Editor && parameterHintsVisible && !suggestWidgetVisible',
    'editor::SignatureHelpPrevious',
  ],
  [
    552,
    'linux',
    'ArrowDown',
    'editor.showNextParameterHint',
    'Editor && parameterHintsVisible && !suggestWidgetVisible',
    'editor::SignatureHelpNext',
  ],
  [
    561,
    'linux',
    'Ctrl+Shift+E',
    'workspace.revealActiveFileInTree',
    '!Chat > Editor && mode == full',
    'pane::RevealInProjectPanel',
  ],
  [593, 'linux', 'Ctrl+N', 'fileTree.newFile', 'Sidebar > FileTree', 'project_panel::NewFile'],
  [
    595,
    'linux',
    'Alt+Ctrl+N',
    'fileTree.newFolder',
    'Sidebar > FileTree',
    'project_panel::NewDirectory',
  ],
  [608, 'linux', 'UNDO', 'fileTree.undo', 'Sidebar > FileTree', 'project_panel::Undo'],
  [609, 'linux', 'Ctrl+Z', 'fileTree.undo', 'Sidebar > FileTree', 'project_panel::Undo'],
  [611, 'linux', 'Ctrl+Shift+Z', 'fileTree.redo', 'Sidebar > FileTree', 'project_panel::Redo'],
  [612, 'linux', 'Enter', 'fileTree.rename', 'Sidebar > FileTree', 'project_panel::Rename'],
  [613, 'linux', 'F2', 'fileTree.rename', 'Sidebar > FileTree', 'project_panel::Rename'],
  [675, 'linux', 'Ctrl+Enter', 'git.commit', 'Sidebar > Git', 'git::Commit'],
  [
    730,
    'linux',
    'Ctrl+P',
    'workspace.showQuickAccess',
    '(CommandPalette && mode == files) || ((CommandPalette && mode == files) > Editor)',
    'file_finder::Toggle',
  ],
  [745, 'linux', 'Copy', 'terminal.copy', 'Terminal', 'terminal::Copy'],
  [746, 'linux', 'Ctrl+Insert', 'terminal.copy', 'Terminal', 'terminal::Copy'],
  [747, 'linux', 'Ctrl+Shift+C', 'terminal.copy', 'Terminal', 'terminal::Copy'],
  [748, 'linux', 'Paste', 'terminal.paste', 'Terminal', 'terminal::Paste'],
  [749, 'linux', 'Shift+Insert', 'terminal.paste', 'Terminal', 'terminal::Paste'],
  [750, 'linux', 'Ctrl+Shift+V', 'terminal.paste', 'Terminal', 'terminal::Paste'],
  [
    752,
    'linux',
    'Alt+B',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendText","\\u001bb"]',
    { text: '\u001bb' },
  ],
  [
    753,
    'linux',
    'Alt+F',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendText","\\u001bf"]',
    { text: '\u001bf' },
  ],
  [
    754,
    'linux',
    'Alt+.',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendText","\\u001b."]',
    { text: '\u001b.' },
  ],
  [
    755,
    'linux',
    'Ctrl+Delete',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendText","\\u001b[3;5~"]',
    { text: '\u001b[3;5~' },
  ],
  [
    756,
    'linux',
    'Ctrl+B',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-b"]',
    { keystroke: 'ctrl-b' },
  ],
  [
    757,
    'linux',
    'Ctrl+C',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-c"]',
    { keystroke: 'ctrl-c' },
  ],
  [
    758,
    'linux',
    'Ctrl+E',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-e"]',
    { keystroke: 'ctrl-e' },
  ],
  [
    759,
    'linux',
    'Ctrl+O',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-o"]',
    { keystroke: 'ctrl-o' },
  ],
  [
    760,
    'linux',
    'Ctrl+Q',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-q"]',
    { keystroke: 'ctrl-q' },
  ],
  [
    761,
    'linux',
    'Ctrl+W',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-w"]',
    { keystroke: 'ctrl-w' },
  ],
  [
    762,
    'linux',
    'Ctrl+R',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-r"]',
    { keystroke: 'ctrl-r' },
  ],
  [
    763,
    'linux',
    'Ctrl+Backspace',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-w"]',
    { keystroke: 'ctrl-w' },
  ],
  [767, 'linux', 'Ctrl+Shift+L', 'terminal.clear', 'Terminal', 'terminal::Clear'],
  [768, 'linux', 'Ctrl+Shift+W', 'workspace.killTerminal', 'Terminal', 'pane::CloseActiveItem'],
  [
    769,
    'linux',
    'ArrowUp',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","up"]',
    { keystroke: 'up' },
  ],
  [
    770,
    'linux',
    'PageUp',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","pageup"]',
    { keystroke: 'pageup' },
  ],
  [
    771,
    'linux',
    'ArrowDown',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","down"]',
    { keystroke: 'down' },
  ],
  [
    772,
    'linux',
    'PageDown',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","pagedown"]',
    { keystroke: 'pagedown' },
  ],
  [
    773,
    'linux',
    'Escape',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","escape"]',
    { keystroke: 'escape' },
  ],
  [
    774,
    'linux',
    'Enter',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","enter"]',
    { keystroke: 'enter' },
  ],
  [788, 'linux', 'Ctrl+N', 'workspace.newChat', 'Chat > Terminal', 'agent::NewThread'],
  [
    797,
    'linux',
    'Ctrl+Tab',
    'workspace.nextItem',
    'CommandPalette && mode == scripts',
    'pane::ActivateNextItem',
  ],
  [
    798,
    'linux',
    'Ctrl+Shift+Tab',
    'workspace.previousItem',
    'CommandPalette && mode == scripts',
    'pane::ActivatePreviousItem',
  ],
  [847, 'linux', 'Ctrl+,', 'workspace.showSettings', 'Workspace && !Settings', 'zed::OpenSettings'],
  [985, 'mac', 'Shift+Backspace', 'editor.deleteBackward', 'Editor', 'editor::Backspace'],
  [986, 'mac', 'Ctrl+H', 'editor.deleteBackward', 'Editor', 'editor::Backspace'],
  [987, 'mac', 'Backspace', 'editor.deleteBackward', 'Editor', 'editor::Backspace'],
  [988, 'mac', 'Ctrl+D', 'editor.deleteForward', 'Editor', 'editor::Delete'],
  [989, 'mac', 'Delete', 'editor.deleteForward', 'Editor', 'editor::Delete'],
  [990, 'mac', 'Tab', 'editor.indentSelection', 'Editor', 'editor::Tab'],
  [991, 'mac', 'Shift+Tab', 'editor.outdentSelection', 'Editor', 'editor::Backtab'],
  [
    999,
    'mac',
    'Alt+Backspace',
    'editor.deleteWordLeft',
    'Editor',
    '["editor::DeleteToPreviousWordStart",{"ignore_newlines":false,"ignore_brackets":false}]',
  ],
  [
    1000,
    'mac',
    'Ctrl+W',
    'editor.deleteWordLeft',
    'Editor',
    '["editor::DeleteToPreviousWordStart",{"ignore_newlines":false,"ignore_brackets":false}]',
  ],
  [
    1001,
    'mac',
    'Alt+Delete',
    'editor.deleteWordRight',
    'Editor',
    '["editor::DeleteToNextWordEnd",{"ignore_newlines":false,"ignore_brackets":false}]',
  ],
  [1005, 'mac', 'Meta+Z', 'editor.undo', 'Editor', 'editor::Undo'],
  [1006, 'mac', 'Meta+Shift+Z', 'editor.redo', 'Editor', 'editor::Redo'],
  [1007, 'mac', 'ArrowUp', 'editor.cursorUp', 'Editor', 'editor::MoveUp'],
  [1009, 'mac', 'PageUp', 'editor.cursorPageUp', 'Editor', 'editor::MovePageUp'],
  [1010, 'mac', 'Shift+PageUp', 'editor.selectPageUp', 'Editor', 'editor::SelectPageUp'],
  [1013, 'mac', 'ArrowDown', 'editor.cursorDown', 'Editor', 'editor::MoveDown'],
  [1015, 'mac', 'PageDown', 'editor.cursorPageDown', 'Editor', 'editor::MovePageDown'],
  [1016, 'mac', 'Shift+PageDown', 'editor.selectPageDown', 'Editor', 'editor::SelectPageDown'],
  [1019, 'mac', 'Ctrl+P', 'editor.cursorUp', 'Editor', 'editor::MoveUp'],
  [1020, 'mac', 'Ctrl+N', 'editor.cursorDown', 'Editor', 'editor::MoveDown'],
  [1021, 'mac', 'Ctrl+B', 'editor.cursorLeft', 'Editor', 'editor::MoveLeft'],
  [1022, 'mac', 'ArrowLeft', 'editor.cursorLeft', 'Editor', 'editor::MoveLeft'],
  [1023, 'mac', 'Ctrl+F', 'editor.cursorRight', 'Editor', 'editor::MoveRight'],
  [1024, 'mac', 'ArrowRight', 'editor.cursorRight', 'Editor', 'editor::MoveRight'],
  [
    1026,
    'mac',
    'Alt+ArrowLeft',
    'editor.cursorWordLeft',
    'Editor',
    'editor::MoveToPreviousWordStart',
  ],
  [1027, 'mac', 'Alt+ArrowRight', 'editor.cursorWordRight', 'Editor', 'editor::MoveToNextWordEnd'],
  [
    1028,
    'mac',
    'Meta+ArrowLeft',
    'editor.cursorLineStart',
    'Editor',
    '["editor::MoveToBeginningOfLine",{"stop_at_soft_wraps":true,"stop_at_indent":true}]',
  ],
  [
    1029,
    'mac',
    'Ctrl+A',
    'editor.cursorLineStart',
    'Editor',
    '["editor::MoveToBeginningOfLine",{"stop_at_soft_wraps":false,"stop_at_indent":true}]',
  ],
  [
    1030,
    'mac',
    'Home',
    'editor.cursorLineStart',
    'Editor',
    '["editor::MoveToBeginningOfLine",{"stop_at_soft_wraps":true,"stop_at_indent":true}]',
  ],
  [
    1031,
    'mac',
    'Meta+ArrowRight',
    'editor.cursorLineEnd',
    'Editor',
    '["editor::MoveToEndOfLine",{"stop_at_soft_wraps":true}]',
  ],
  [
    1032,
    'mac',
    'Ctrl+E',
    'editor.cursorLineEnd',
    'Editor',
    '["editor::MoveToEndOfLine",{"stop_at_soft_wraps":false}]',
  ],
  [
    1033,
    'mac',
    'End',
    'editor.cursorLineEnd',
    'Editor',
    '["editor::MoveToEndOfLine",{"stop_at_soft_wraps":true}]',
  ],
  [1034, 'mac', 'Meta+ArrowUp', 'editor.cursorDocumentStart', 'Editor', 'editor::MoveToBeginning'],
  [1035, 'mac', 'Meta+ArrowDown', 'editor.cursorDocumentEnd', 'Editor', 'editor::MoveToEnd'],
  [1036, 'mac', 'Meta+Home', 'editor.cursorDocumentStart', 'Editor', 'editor::MoveToBeginning'],
  [1037, 'mac', 'Meta+End', 'editor.cursorDocumentEnd', 'Editor', 'editor::MoveToEnd'],
  [1038, 'mac', 'Shift+ArrowUp', 'editor.selectUp', 'Editor', 'editor::SelectUp'],
  [1039, 'mac', 'Ctrl+Shift+P', 'editor.selectUp', 'Editor', 'editor::SelectUp'],
  [1040, 'mac', 'Shift+ArrowDown', 'editor.selectDown', 'Editor', 'editor::SelectDown'],
  [1041, 'mac', 'Ctrl+Shift+N', 'editor.selectDown', 'Editor', 'editor::SelectDown'],
  [1042, 'mac', 'Shift+ArrowLeft', 'editor.selectLeft', 'Editor', 'editor::SelectLeft'],
  [1043, 'mac', 'Ctrl+Shift+B', 'editor.selectLeft', 'Editor', 'editor::SelectLeft'],
  [1044, 'mac', 'Shift+ArrowRight', 'editor.selectRight', 'Editor', 'editor::SelectRight'],
  [1045, 'mac', 'Ctrl+Shift+F', 'editor.selectRight', 'Editor', 'editor::SelectRight'],
  [
    1046,
    'mac',
    'Alt+Shift+ArrowLeft',
    'editor.selectWordLeft',
    'Editor',
    'editor::SelectToPreviousWordStart',
  ],
  [
    1047,
    'mac',
    'Alt+Shift+ArrowRight',
    'editor.selectWordRight',
    'Editor',
    'editor::SelectToNextWordEnd',
  ],
  [
    1050,
    'mac',
    'Meta+Shift+ArrowUp',
    'editor.selectDocumentStart',
    'Editor',
    'editor::SelectToBeginning',
  ],
  [
    1051,
    'mac',
    'Meta+Shift+ArrowDown',
    'editor.selectDocumentEnd',
    'Editor',
    'editor::SelectToEnd',
  ],
  [1052, 'mac', 'Meta+A', 'editor.selectAll', 'Editor', 'editor::SelectAll'],
  [1054, 'mac', 'Meta+Shift+I', 'editor.action.formatDocument', 'Editor', 'editor::Format'],
  [
    1056,
    'mac',
    'Meta+Shift+ArrowLeft',
    'editor.selectLineStart',
    'Editor',
    '["editor::SelectToBeginningOfLine",{"stop_at_soft_wraps":true,"stop_at_indent":true}]',
  ],
  [
    1057,
    'mac',
    'Shift+Home',
    'editor.selectLineStart',
    'Editor',
    '["editor::SelectToBeginningOfLine",{"stop_at_soft_wraps":true,"stop_at_indent":true}]',
  ],
  [
    1058,
    'mac',
    'Ctrl+Shift+A',
    'editor.selectLineStart',
    'Editor',
    '["editor::SelectToBeginningOfLine",{"stop_at_soft_wraps":true,"stop_at_indent":true}]',
  ],
  [
    1059,
    'mac',
    'Meta+Shift+ArrowRight',
    'editor.selectLineEnd',
    'Editor',
    '["editor::SelectToEndOfLine",{"stop_at_soft_wraps":true}]',
  ],
  [
    1060,
    'mac',
    'Shift+End',
    'editor.selectLineEnd',
    'Editor',
    '["editor::SelectToEndOfLine",{"stop_at_soft_wraps":true}]',
  ],
  [
    1061,
    'mac',
    'Ctrl+Shift+E',
    'editor.selectLineEnd',
    'Editor',
    '["editor::SelectToEndOfLine",{"stop_at_soft_wraps":true}]',
  ],
  [
    1062,
    'mac',
    'Ctrl+V',
    'editor.cursorPageDown',
    'Editor',
    '["editor::MovePageDown",{"center_cursor":true}]',
  ],
  [
    1063,
    'mac',
    'Ctrl+Shift+V',
    'editor.cursorPageUp',
    'Editor',
    '["editor::MovePageUp",{"center_cursor":true}]',
  ],
  [
    1079,
    'mac',
    'Meta+Enter',
    'editor.action.insertLineAfter',
    'Editor && mode == full',
    'editor::NewlineBelow',
  ],
  [
    1080,
    'mac',
    'Meta+Shift+Enter',
    'editor.action.insertLineBefore',
    'Editor && mode == full',
    'editor::NewlineAbove',
  ],
  [
    1081,
    'mac',
    'Meta+K Z',
    'editor.action.toggleWordWrap',
    'Editor && mode == full',
    'editor::ToggleSoftWrap',
  ],
  [1082, 'mac', 'Meta+F', 'editor.find', 'Editor && mode == full', 'buffer_search::Deploy'],
  [
    1083,
    'mac',
    'Meta+Alt+L',
    'editor.find',
    'Editor && mode == full',
    '["buffer_search::Deploy",{"selection_search_enabled":true}]',
  ],
  [
    1085,
    'mac',
    'Meta+>',
    'workspace.addSelectionToChat',
    'Editor && mode == full',
    'agent::AddSelectionToThread',
  ],
  [
    1098,
    'mac',
    'Ctrl+Shift+Enter',
    'editor.action.insertLineAfter',
    'Editor && mode == single_line',
    'editor::NewlineBelow',
  ],
  [1117, 'mac', 'Meta+N', 'workspace.newChat', 'Chat', 'agent::NewThread'],
  [1118, 'mac', 'Meta+Alt+C', 'workspace.showSettings', 'Chat', 'agent::OpenSettings'],
  [1121, 'mac', 'Meta+Shift+E', 'workspace.focusFileTree', 'Chat', 'project_panel::ToggleFocus'],
  [1128, 'mac', 'Meta+N', 'workspace.newChat', 'Chat', 'agent::NewThread'],
  [1129, 'mac', 'Ctrl+-', 'workspace.navigateBack', 'Chat', 'pane::GoBack'],
  [1137, 'mac', 'Meta+>', 'workspace.addSelectionToChat', 'Chat', 'agent::AddSelectionToThread'],
  [
    1206,
    'mac',
    'Enter',
    'chat.sendMessage',
    'Chat > Editor && !use_modifier_to_send',
    'agent::Chat',
  ],
  [1215, 'mac', 'Escape', 'editor.closeFind', 'Editor > FindWidget', 'buffer_search::Dismiss'],
  [
    1216,
    'mac',
    'Tab',
    'workspace.focusEditor',
    'Editor > FindWidget',
    'buffer_search::FocusEditor',
  ],
  [1217, 'mac', 'Enter', 'editor.findNext', 'Editor > FindWidget', 'search::SelectNextMatch'],
  [
    1218,
    'mac',
    'Shift+Enter',
    'editor.findPrevious',
    'Editor > FindWidget',
    'search::SelectPreviousMatch',
  ],
  [
    1220,
    'mac',
    'Alt+Enter',
    'editor.selectAllMatches',
    'Editor > FindWidget',
    'search::SelectAllMatches',
  ],
  [
    1222,
    'mac',
    'Meta+Alt+L',
    'editor.toggleFindInSelection',
    'Editor > FindWidget',
    'search::ToggleSelection',
  ],
  [1223, 'mac', 'Meta+Shift+O', 'workspace.gotoSymbol', 'Editor > FindWidget', 'outline::Toggle'],
  [1225, 'mac', 'Enter', 'editor.replaceOne', 'Editor > ReplaceInput', 'search::ReplaceNext'],
  [1226, 'mac', 'Meta+Enter', 'editor.replaceAll', 'Editor > ReplaceInput', 'search::ReplaceAll'],
  [
    1228,
    'mac',
    'Shift+Enter',
    'editor.findPrevious',
    'Editor > (FindWidget && !ReplaceInput)',
    'search::SelectPreviousMatch',
  ],
  [
    1252,
    'mac',
    'Alt+Meta+ArrowLeft',
    'workspace.previousItem',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::ActivatePreviousItem',
  ],
  [
    1253,
    'mac',
    'Meta+{',
    'workspace.previousItem',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::ActivatePreviousItem',
  ],
  [
    1254,
    'mac',
    'Alt+Meta+ArrowRight',
    'workspace.nextItem',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::ActivateNextItem',
  ],
  [
    1255,
    'mac',
    'Meta+}',
    'workspace.nextItem',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::ActivateNextItem',
  ],
  [
    1258,
    'mac',
    'Meta+W',
    'workspace.closeCurrentTab',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::CloseActiveItem",{"close_pinned":false}]',
  ],
  [
    1267,
    'mac',
    'Meta+G',
    'editor.findNext',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::SelectNextMatch',
  ],
  [
    1268,
    'mac',
    'Meta+Shift+G',
    'editor.findPrevious',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::SelectPreviousMatch',
  ],
  [
    1270,
    'mac',
    'Meta+Alt+L',
    'editor.toggleFindInSelection',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::ToggleSelection',
  ],
  [
    1271,
    'mac',
    'Alt+Enter',
    'editor.selectAllMatches',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::SelectAllMatches',
  ],
  [
    1272,
    'mac',
    'Alt+Meta+C',
    'editor.toggleFindCaseSensitive',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::ToggleCaseSensitive',
  ],
  [
    1273,
    'mac',
    'Alt+Meta+W',
    'editor.toggleFindWholeWord',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::ToggleWholeWord',
  ],
  [
    1274,
    'mac',
    'Alt+Meta+X',
    'editor.toggleFindRegex',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'search::ToggleRegex',
  ],
  [1276, 'mac', 'Meta+[', 'editor.action.outdentLines', 'Editor', 'editor::Outdent'],
  [1277, 'mac', 'Meta+]', 'editor.action.indentLines', 'Editor', 'editor::Indent'],
  [
    1278,
    'mac',
    'Meta+Ctrl+P',
    'editor.action.insertCursorAbove',
    'Editor',
    '["editor::AddSelectionAbove",{"skip_soft_wrap":false}]',
  ],
  [
    1279,
    'mac',
    'Meta+Alt+ArrowUp',
    'editor.action.insertCursorAbove',
    'Editor',
    '["editor::AddSelectionAbove",{"skip_soft_wrap":true}]',
  ],
  [
    1280,
    'mac',
    'Meta+Ctrl+N',
    'editor.action.insertCursorBelow',
    'Editor',
    '["editor::AddSelectionBelow",{"skip_soft_wrap":false}]',
  ],
  [
    1281,
    'mac',
    'Meta+Alt+ArrowDown',
    'editor.action.insertCursorBelow',
    'Editor',
    '["editor::AddSelectionBelow",{"skip_soft_wrap":true}]',
  ],
  [1282, 'mac', 'Meta+Shift+K', 'editor.action.deleteLines', 'Editor', 'editor::DeleteLine'],
  [1283, 'mac', 'Alt+ArrowUp', 'editor.action.moveLinesUpAction', 'Editor', 'editor::MoveLineUp'],
  [
    1284,
    'mac',
    'Alt+ArrowDown',
    'editor.action.moveLinesDownAction',
    'Editor',
    'editor::MoveLineDown',
  ],
  [
    1285,
    'mac',
    'Alt+Shift+ArrowUp',
    'editor.action.copyLinesUpAction',
    'Editor',
    'editor::DuplicateLineUp',
  ],
  [
    1286,
    'mac',
    'Alt+Shift+ArrowDown',
    'editor.action.copyLinesDownAction',
    'Editor',
    'editor::DuplicateLineDown',
  ],
  [
    1287,
    'mac',
    'Meta+Ctrl+ArrowLeft',
    'editor.action.smartSelect.shrink',
    'Editor',
    'editor::SelectSmallerSyntaxNode',
  ],
  [
    1288,
    'mac',
    'Meta+Ctrl+ArrowRight',
    'editor.action.smartSelect.expand',
    'Editor',
    'editor::SelectLargerSyntaxNode',
  ],
  [
    1290,
    'mac',
    'Ctrl+Shift+ArrowRight',
    'editor.action.smartSelect.expand',
    'Editor',
    'editor::SelectLargerSyntaxNode',
  ],
  [
    1291,
    'mac',
    'Ctrl+Shift+ArrowLeft',
    'editor.action.smartSelect.shrink',
    'Editor',
    'editor::SelectSmallerSyntaxNode',
  ],
  [
    1293,
    'mac',
    'Meta+D',
    'editor.addNextOccurrence',
    'Editor',
    '["editor::SelectNext",{"replace_newest":false}]',
  ],
  [
    1294,
    'mac',
    'Meta+Shift+L',
    'editor.action.selectHighlights',
    'Editor',
    'editor::SelectAllMatches',
  ],
  [1295, 'mac', 'Meta+F2', 'editor.action.selectHighlights', 'Editor', 'editor::SelectAllMatches'],
  [
    1296,
    'mac',
    'Meta+K Meta+D',
    'editor.action.moveSelectionToNextFindMatch',
    'Editor',
    '["editor::SelectNext",{"replace_newest":true}]',
  ],
  [1299, 'mac', 'Meta+K Meta+I', 'editor.action.showHover', 'Editor', 'editor::Hover'],
  [
    1301,
    'mac',
    'Meta+/',
    'editor.action.commentLine',
    'Editor',
    '["editor::ToggleComments",{"advance_downwards":false,"comment_empty_lines":true}]',
  ],
  [
    1302,
    'mac',
    'Meta+K Meta+/',
    'editor.action.blockComment',
    'Editor',
    'editor::ToggleBlockComments',
  ],
  [
    1303,
    'mac',
    'Shift+Alt+A',
    'editor.action.blockComment',
    'Editor',
    'editor::ToggleBlockComments',
  ],
  [
    1304,
    'mac',
    'F8',
    'editor.action.marker.next',
    'Editor',
    '["editor::GoToDiagnostic",{"severity":{"min":"hint","max":"error"}}]',
  ],
  [
    1305,
    'mac',
    'Shift+F8',
    'editor.action.marker.prev',
    'Editor',
    '["editor::GoToPreviousDiagnostic",{"severity":{"min":"hint","max":"error"}}]',
  ],
  [1306, 'mac', 'F2', 'editor.action.rename', 'Editor', 'editor::Rename'],
  [1307, 'mac', 'F12', 'editor.action.goToDefinition', 'Editor', 'editor::GoToDefinition'],
  [
    1308,
    'mac',
    'Alt+F12',
    'editor.action.revealDefinitionAside',
    'Editor',
    'editor::GoToDefinitionSplit',
  ],
  [
    1309,
    'mac',
    'Meta+F12',
    'editor.action.goToTypeDefinition',
    'Editor',
    'editor::GoToTypeDefinition',
  ],
  [
    1310,
    'mac',
    'Shift+F12',
    'editor.action.goToImplementation',
    'Editor',
    'editor::GoToImplementation',
  ],
  [
    1312,
    'mac',
    'Alt+Shift+F12',
    'editor.action.goToReferences',
    'Editor',
    'editor::FindAllReferences',
  ],
  [
    1314,
    'mac',
    'Meta+|',
    'editor.action.jumpToBracket',
    'Editor',
    'editor::MoveToEnclosingBracket',
  ],
  [
    1315,
    'mac',
    'Ctrl+M',
    'editor.action.jumpToBracket',
    'Editor',
    'editor::MoveToEnclosingBracket',
  ],
  [1316, 'mac', 'Alt+Meta+[', 'editor.fold', 'Editor', 'editor::Fold'],
  [1317, 'mac', 'Alt+Meta+]', 'editor.unfold', 'Editor', 'editor::UnfoldLines'],
  [1319, 'mac', 'Meta+K Meta+[', 'editor.foldRecursively', 'Editor', 'editor::FoldRecursive'],
  [1320, 'mac', 'Meta+K Meta+]', 'editor.unfoldRecursively', 'Editor', 'editor::UnfoldRecursive'],
  [1321, 'mac', 'Meta+K Meta+1', 'editor.foldLevel1', 'Editor', 'editor::FoldAtLevel_1'],
  [1322, 'mac', 'Meta+K Meta+2', 'editor.foldLevel2', 'Editor', 'editor::FoldAtLevel_2'],
  [1323, 'mac', 'Meta+K Meta+3', 'editor.foldLevel3', 'Editor', 'editor::FoldAtLevel_3'],
  [1324, 'mac', 'Meta+K Meta+4', 'editor.foldLevel4', 'Editor', 'editor::FoldAtLevel_4'],
  [1325, 'mac', 'Meta+K Meta+5', 'editor.foldLevel5', 'Editor', 'editor::FoldAtLevel_5'],
  [1326, 'mac', 'Meta+K Meta+6', 'editor.foldLevel6', 'Editor', 'editor::FoldAtLevel_6'],
  [1327, 'mac', 'Meta+K Meta+7', 'editor.foldLevel7', 'Editor', 'editor::FoldAtLevel_7'],
  [1330, 'mac', 'Meta+K Meta+0', 'editor.foldAll', 'Editor', 'editor::FoldAll'],
  [1331, 'mac', 'Meta+K Meta+J', 'editor.unfoldAll', 'Editor', 'editor::UnfoldAll'],
  [1332, 'mac', 'Ctrl+Space', 'editor.action.triggerSuggest', 'Editor', 'editor::ShowCompletions'],
  [1337, 'mac', 'Meta+\\', 'workspace.splitEditorRight', 'Editor', 'pane::SplitRight'],
  [
    1344,
    'mac',
    'Meta+Shift+O',
    'workspace.gotoSymbol',
    'Editor && mode == full',
    'outline::Toggle',
  ],
  [1345, 'mac', 'Ctrl+G', 'workspace.goToLine', 'Editor && mode == full', 'go_to_line::Toggle'],
  [
    1348,
    'mac',
    'Ctrl+1',
    'workspace.selectItem1',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",0]',
  ],
  [
    1349,
    'mac',
    'Ctrl+2',
    'workspace.selectItem2',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",1]',
  ],
  [
    1350,
    'mac',
    'Ctrl+3',
    'workspace.selectItem3',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",2]',
  ],
  [
    1351,
    'mac',
    'Ctrl+4',
    'workspace.selectItem4',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",3]',
  ],
  [
    1352,
    'mac',
    'Ctrl+5',
    'workspace.selectItem5',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",4]',
  ],
  [
    1353,
    'mac',
    'Ctrl+6',
    'workspace.selectItem6',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",5]',
  ],
  [
    1354,
    'mac',
    'Ctrl+7',
    'workspace.selectItem7',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",6]',
  ],
  [
    1355,
    'mac',
    'Ctrl+8',
    'workspace.selectItem8',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    '["pane::ActivateItem",7]',
  ],
  [
    1357,
    'mac',
    'Ctrl+0',
    'workspace.selectItem9',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::ActivateLastItem',
  ],
  [
    1358,
    'mac',
    'Ctrl+-',
    'workspace.navigateBack',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::GoBack',
  ],
  [
    1359,
    'mac',
    'Ctrl+_',
    'workspace.navigateForward',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::GoForward',
  ],
  [1373, 'mac', 'Ctrl+~', 'workspace.newTerminal', 'Workspace', 'workspace::NewTerminal'],
  [1374, 'mac', 'Meta+S', 'workspace.saveFile', 'Workspace', 'workspace::Save'],
  [1379, 'mac', 'Ctrl+`', 'workspace.revealTerminal', 'Workspace', 'terminal_panel::Toggle'],
  [
    1380,
    'mac',
    'Meta+1',
    'workspace.focusFirstEditorGroup',
    'Workspace',
    '["workspace::ActivatePane",0]',
  ],
  [
    1381,
    'mac',
    'Meta+2',
    'workspace.focusSecondEditorGroup',
    'Workspace',
    '["workspace::ActivatePane",1]',
  ],
  [
    1382,
    'mac',
    'Meta+3',
    'workspace.focusThirdEditorGroup',
    'Workspace',
    '["workspace::ActivatePane",2]',
  ],
  [
    1389,
    'mac',
    'Meta+B',
    'workspace.toggleSidebarVisibility',
    'Workspace',
    'workspace::ToggleLeftDock',
  ],
  [1392, 'mac', 'Meta+J', 'workspace.togglePanel', 'Workspace', 'workspace::ToggleBottomDock'],
  [
    1393,
    'mac',
    'Meta+Alt+J',
    'workspace.toggleSessionRail',
    'Workspace',
    'multi_workspace::ToggleWorkspaceSidebar',
  ],
  [
    1404,
    'mac',
    'Meta+Shift+T',
    'workspace.reopenClosedEditor',
    'Workspace',
    'pane::ReopenClosedItem',
  ],
  [
    1407,
    'mac',
    'Meta+K Meta+T',
    'workspace.selectThemeBundle',
    'Workspace',
    'theme_selector::Toggle',
  ],
  [1411, 'mac', 'Meta+P', 'workspace.showQuickAccess', 'Workspace', 'file_finder::Toggle'],
  [
    1414,
    'mac',
    'Meta+Shift+P',
    'workspace.showCommandPalette',
    'Workspace',
    'command_palette::Toggle',
  ],
  [
    1416,
    'mac',
    'Meta+Shift+E',
    'workspace.focusFileTree',
    'Workspace',
    'project_panel::ToggleFocus',
  ],
  [1418, 'mac', 'Ctrl+Shift+G', 'workspace.focusGit', 'Workspace', 'git_panel::ToggleFocus'],
  [1420, 'mac', 'Meta+?', 'workspace.revealChat', 'Workspace', 'agent::ToggleFocus'],
  [1421, 'mac', 'Meta+Alt+S', 'workspace.saveAllFiles', 'Workspace', 'workspace::SaveAll'],
  [
    1436,
    'mac',
    'Meta+W',
    'workspace.closeCurrentTab',
    'Workspace',
    '["pane::CloseActiveItem",{"close_pinned":false}]',
  ],
  [1463, 'mac', 'Meta+U', 'editor.cursorUndo', 'Editor', 'editor::UndoSelection'],
  [1464, 'mac', 'Meta+Shift+U', 'editor.cursorRedo', 'Editor', 'editor::RedoSelection'],
  [1465, 'mac', 'Ctrl+J', 'editor.action.joinLines', 'Editor', 'editor::JoinLines'],
  [
    1466,
    'mac',
    'Ctrl+Alt+Backspace',
    'editor.deleteWordPartLeft',
    'Editor',
    'editor::DeleteToPreviousSubwordStart',
  ],
  [
    1467,
    'mac',
    'Ctrl+Alt+H',
    'editor.deleteWordPartLeft',
    'Editor',
    'editor::DeleteToPreviousSubwordStart',
  ],
  [
    1468,
    'mac',
    'Ctrl+Alt+Delete',
    'editor.deleteWordPartRight',
    'Editor',
    'editor::DeleteToNextSubwordEnd',
  ],
  [
    1469,
    'mac',
    'Ctrl+Alt+D',
    'editor.deleteWordPartRight',
    'Editor',
    'editor::DeleteToNextSubwordEnd',
  ],
  [
    1470,
    'mac',
    'Ctrl+Alt+ArrowLeft',
    'editor.cursorWordPartLeft',
    'Editor',
    'editor::MoveToPreviousSubwordStart',
  ],
  [
    1471,
    'mac',
    'Ctrl+Alt+B',
    'editor.cursorWordPartLeft',
    'Editor',
    'editor::MoveToPreviousSubwordStart',
  ],
  [
    1472,
    'mac',
    'Ctrl+Alt+ArrowRight',
    'editor.cursorWordPartRight',
    'Editor',
    'editor::MoveToNextSubwordEnd',
  ],
  [
    1473,
    'mac',
    'Ctrl+Alt+F',
    'editor.cursorWordPartRight',
    'Editor',
    'editor::MoveToNextSubwordEnd',
  ],
  [
    1474,
    'mac',
    'Ctrl+Alt+Shift+ArrowLeft',
    'editor.cursorWordPartLeftSelect',
    'Editor',
    'editor::SelectToPreviousSubwordStart',
  ],
  [
    1475,
    'mac',
    'Ctrl+Alt+Shift+B',
    'editor.cursorWordPartLeftSelect',
    'Editor',
    'editor::SelectToPreviousSubwordStart',
  ],
  [
    1476,
    'mac',
    'Ctrl+Alt+Shift+ArrowRight',
    'editor.cursorWordPartRightSelect',
    'Editor',
    'editor::SelectToNextSubwordEnd',
  ],
  [
    1477,
    'mac',
    'Ctrl+Alt+Shift+F',
    'editor.cursorWordPartRightSelect',
    'Editor',
    'editor::SelectToNextSubwordEnd',
  ],
  [
    1479,
    'mac',
    'Meta+K ArrowDown',
    'workspace.splitEditorDown',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::SplitDown',
  ],
  [
    1481,
    'mac',
    'Meta+K ArrowRight',
    'workspace.splitEditorRight',
    '(Editor || Terminal || Chat || Settings || Problems || Search)',
    'pane::SplitRight',
  ],
  [
    1484,
    'mac',
    'Enter',
    'editor.acceptSelectedSuggestion',
    'Editor && suggestWidgetVisible',
    'editor::ConfirmCompletion',
  ],
  [
    1489,
    'mac',
    'Alt+Tab',
    'editor.action.inlineSuggest.commit',
    'Editor && inlineSuggestionVisible',
    'editor::AcceptEditPrediction',
  ],
  [
    1490,
    'mac',
    'Ctrl+Meta+ArrowRight',
    'editor.action.inlineSuggest.acceptNextWord',
    'Editor && inlineSuggestionVisible',
    'editor::AcceptNextWordEditPrediction',
  ],
  [
    1494,
    'mac',
    'ArrowUp',
    'editor.selectPrevSuggestion',
    'Editor && (showing_code_actions || suggestWidgetVisible)',
    'editor::ContextMenuPrevious',
  ],
  [
    1495,
    'mac',
    'Ctrl+P',
    'editor.selectPrevSuggestion',
    'Editor && (showing_code_actions || suggestWidgetVisible)',
    'editor::ContextMenuPrevious',
  ],
  [
    1496,
    'mac',
    'ArrowDown',
    'editor.selectNextSuggestion',
    'Editor && (showing_code_actions || suggestWidgetVisible)',
    'editor::ContextMenuNext',
  ],
  [
    1497,
    'mac',
    'Ctrl+N',
    'editor.selectNextSuggestion',
    'Editor && (showing_code_actions || suggestWidgetVisible)',
    'editor::ContextMenuNext',
  ],
  [
    1500,
    'mac',
    'ArrowUp',
    'editor.showPrevParameterHint',
    'Editor && parameterHintsVisible && !suggestWidgetVisible',
    'editor::SignatureHelpPrevious',
  ],
  [
    1501,
    'mac',
    'ArrowDown',
    'editor.showNextParameterHint',
    'Editor && parameterHintsVisible && !suggestWidgetVisible',
    'editor::SignatureHelpNext',
  ],
  [
    1510,
    'mac',
    'Meta+Shift+E',
    'workspace.revealActiveFileInTree',
    '!Chat > Editor && mode == full',
    'pane::RevealInProjectPanel',
  ],
  [1541, 'mac', 'Meta+N', 'fileTree.newFile', 'Sidebar > FileTree', 'project_panel::NewFile'],
  [
    1543,
    'mac',
    'Alt+Meta+N',
    'fileTree.newFolder',
    'Sidebar > FileTree',
    'project_panel::NewDirectory',
  ],
  [1549, 'mac', 'Meta+Z', 'fileTree.undo', 'Sidebar > FileTree', 'project_panel::Undo'],
  [1550, 'mac', 'Meta+Shift+Z', 'fileTree.redo', 'Sidebar > FileTree', 'project_panel::Redo'],
  [1551, 'mac', 'Enter', 'fileTree.rename', 'Sidebar > FileTree', 'project_panel::Rename'],
  [1552, 'mac', 'F2', 'fileTree.rename', 'Sidebar > FileTree', 'project_panel::Rename'],
  [1628, 'mac', 'Meta+Enter', 'git.commit', 'Sidebar > Git', 'git::Commit'],
  [1678, 'mac', 'Meta+C', 'terminal.copy', 'Terminal', 'terminal::Copy'],
  [1679, 'mac', 'Meta+V', 'terminal.paste', 'Terminal', 'terminal::Paste'],
  [1683, 'mac', 'Meta+K', 'terminal.clear', 'Terminal', 'terminal::Clear'],
  [1684, 'mac', 'Meta+N', 'workspace.newTerminal', 'Terminal', 'workspace::NewTerminal'],
  [1686, 'mac', 'Ctrl+_', null, 'Terminal', 'null'],
  [
    1687,
    'mac',
    'Meta+Backspace',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-u"]',
    { keystroke: 'ctrl-u' },
  ],
  [
    1688,
    'mac',
    'Alt+Delete',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendText","\\u001bd"]',
    { text: '\u001bd' },
  ],
  [
    1689,
    'mac',
    'Meta+Delete',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-k"]',
    { keystroke: 'ctrl-k' },
  ],
  [
    1690,
    'mac',
    'Meta+ArrowRight',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-e"]',
    { keystroke: 'ctrl-e' },
  ],
  [
    1691,
    'mac',
    'Meta+ArrowLeft',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-a"]',
    { keystroke: 'ctrl-a' },
  ],
  [
    1692,
    'mac',
    'Alt+ArrowLeft',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendText","\\u001bb"]',
    { text: '\u001bb' },
  ],
  [
    1693,
    'mac',
    'Alt+ArrowRight',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendText","\\u001bf"]',
    { text: '\u001bf' },
  ],
  [
    1694,
    'mac',
    'Alt+B',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendText","\\u001bb"]',
    { text: '\u001bb' },
  ],
  [
    1695,
    'mac',
    'Alt+F',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendText","\\u001bf"]',
    { text: '\u001bf' },
  ],
  [
    1696,
    'mac',
    'Ctrl+Delete',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendText","\\u001b[3;5~"]',
    { text: '\u001b[3;5~' },
  ],
  [
    1697,
    'mac',
    'ArrowUp',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","up"]',
    { keystroke: 'up' },
  ],
  [
    1698,
    'mac',
    'PageUp',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","pageup"]',
    { keystroke: 'pageup' },
  ],
  [
    1699,
    'mac',
    'ArrowDown',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","down"]',
    { keystroke: 'down' },
  ],
  [
    1700,
    'mac',
    'PageDown',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","pagedown"]',
    { keystroke: 'pagedown' },
  ],
  [
    1701,
    'mac',
    'Escape',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","escape"]',
    { keystroke: 'escape' },
  ],
  [
    1702,
    'mac',
    'Enter',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","enter"]',
    { keystroke: 'enter' },
  ],
  [
    1703,
    'mac',
    'Ctrl+C',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-c"]',
    { keystroke: 'ctrl-c' },
  ],
  [
    1704,
    'mac',
    'Ctrl+R',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-r"]',
    { keystroke: 'ctrl-r' },
  ],
  [
    1705,
    'mac',
    'Ctrl+Backspace',
    'terminal.sendKeystroke',
    'Terminal',
    '["terminal::SendKeystroke","ctrl-w"]',
    { keystroke: 'ctrl-w' },
  ],
  [1725, 'mac', 'Meta+N', 'workspace.newChat', 'Chat > Terminal', 'agent::NewThread'],
  [
    1742,
    'mac',
    'Ctrl+Tab',
    'workspace.nextItem',
    'CommandPalette && mode == scripts',
    'pane::ActivateNextItem',
  ],
  [
    1743,
    'mac',
    'Ctrl+Shift+Tab',
    'workspace.previousItem',
    'CommandPalette && mode == scripts',
    'pane::ActivatePreviousItem',
  ],
  [1790, 'mac', 'Meta+,', 'workspace.showSettings', 'Workspace && !Settings', 'zed::OpenSettings'],
]

export const oursRuntimePatches: readonly (readonly [
  index: number,
  command: string,
  context: string,
])[] = [
  [329, 'workspace.navigateBack', 'Workspace'],
  [330, 'workspace.navigateForward', 'Workspace'],
  [1276, 'workspace.navigateBack', 'Workspace'],
  [1277, 'workspace.navigateForward', 'Workspace'],
]
