export const SEMANTIC_TOKEN_LEGENDS = [
  // rust-analyzer 1.88.0 — 57 types, 38 of them non-standard.
  {
    serverId: 'rust',
    runtime: 'rust-analyzer 1.88.0',
    tokenTypes: [
      'comment',
      'decorator',
      'enumMember',
      'enum',
      'function',
      'interface',
      'keyword',
      'macro',
      'method',
      'namespace',
      'number',
      'operator',
      'parameter',
      'property',
      'string',
      'struct',
      'typeParameter',
      'variable',
      'type',
      'angle',
      'arithmetic',
      'attributeBracket',
      'attribute',
      'bitwise',
      'boolean',
      'brace',
      'bracket',
      'builtinAttribute',
      'builtinType',
      'character',
      'colon',
      'comma',
      'comparison',
      'constParameter',
      'const',
      'deriveHelper',
      'derive',
      'dot',
      'escapeSequence',
      'formatSpecifier',
      'generic',
      'invalidEscapeSequence',
      'label',
      'lifetime',
      'logical',
      'macroBang',
      'parenthesis',
      'procMacro',
      'punctuation',
      'selfKeyword',
      'selfTypeKeyword',
      'semicolon',
      'static',
      'toolModule',
      'typeAlias',
      'union',
      'unresolvedReference',
    ],
  },
  // gopls v0.21.0 — 14 types. Its custom axis is modifiers, not types.
  {
    serverId: 'gopls',
    runtime: 'gopls 0.21.0',
    tokenTypes: [
      'namespace',
      'type',
      'typeParameter',
      'parameter',
      'variable',
      'function',
      'method',
      'macro',
      'keyword',
      'comment',
      'string',
      'number',
      'operator',
      'label',
    ],
  },
  // zls 0.16.0 — 28 types. `escapeSequence` at index 19 is inserted *between*
  // `string` and `number`, not appended, which is the case that breaks any
  // decoder assuming indices 0-22 are the standard set.
  {
    serverId: 'zls',
    runtime: 'zls 0.16.0',
    tokenTypes: [
      'namespace',
      'type',
      'class',
      'enum',
      'interface',
      'struct',
      'typeParameter',
      'parameter',
      'variable',
      'property',
      'enumMember',
      'event',
      'function',
      'method',
      'macro',
      'keyword',
      'modifier',
      'comment',
      'string',
      'escapeSequence',
      'number',
      'regexp',
      'operator',
      'decorator',
      'errorTag',
      'builtin',
      'label',
      'keywordLiteral',
    ],
  },
  // terraform-ls — 9 types, and only 9 because it intersects its own vocabulary
  // against the `tokenTypes` this client declares.
  {
    serverId: 'terraform',
    runtime: 'terraform-ls',
    tokenTypes: [
      'enumMember',
      'function',
      'keyword',
      'number',
      'parameter',
      'property',
      'string',
      'type',
      'variable',
    ],
  },
  // typescript-language-server — 12 types, `member` the only non-standard one.
  {
    serverId: 'typescript',
    runtime: 'typescript-language-server',
    tokenTypes: [
      'class',
      'enum',
      'interface',
      'namespace',
      'typeParameter',
      'type',
      'parameter',
      'variable',
      'enumMember',
      'property',
      'function',
      'member',
    ],
  },
  // clangd (Apple 15) — 21 entries with duplicates at several indices, which is
  // why nothing anywhere inverts a legend into a name-to-index map.
  {
    serverId: 'clangd',
    runtime: 'Apple clangd 15',
    tokenTypes: [
      'variable',
      'variable',
      'parameter',
      'function',
      'method',
      'function',
      'property',
      'variable',
      'class',
      'interface',
      'enum',
      'enumMember',
      'type',
      'type',
      'unknown',
      'namespace',
      'typeParameter',
      'concept',
      'type',
      'macro',
      'comment',
    ],
  },
  {
    serverId: 'clangd',
    runtime: 'clangd 22.1.8',
    tokenTypes: [
      'variable',
      'variable',
      'parameter',
      'function',
      'method',
      'function',
      'property',
      'variable',
      'class',
      'interface',
      'enum',
      'enumMember',
      'type',
      'type',
      'unknown',
      'namespace',
      'typeParameter',
      'concept',
      'type',
      'macro',
      'modifier',
      'operator',
      'bracket',
      'label',
      'comment',
    ],
  },
  {
    serverId: 'typescript',
    runtime: 'typescript-go 7.0.2',
    tokenTypes: [
      'namespace',
      'class',
      'enum',
      'interface',
      'struct',
      'typeParameter',
      'type',
      'parameter',
      'variable',
      'property',
      'enumMember',
      'decorator',
      'event',
      'function',
      'method',
      'macro',
      'comment',
      'string',
      'keyword',
      'number',
      'regexp',
      'operator',
    ],
  },
] as const
