import { afterEach, expect, test, vi } from 'vitest'
import { lifecycleMachineFixture } from '../../../test/factories/machine-lifecycle'
import { machine, sshServiceFixture } from '../../../test/factories/ssh'

afterEach(() => vi.useRealTimers())

test('renewing a client during release cleanup preserves its other machines', async () => {
  const { service, stopping, releaseStop } = await lifecycleMachineFixture()
  await service.connect('first', 'tab-one')
  await service.connect('second', 'tab-one')
  const controller = new AbortController()
  const events = service.changes('tab-one', controller.signal)
  await events.next()
  vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] })
  controller.abort()
  await events.next()
  await vi.advanceTimersByTimeAsync(30_000)
  vi.useRealTimers()
  await stopping
  const renewedController = new AbortController()
  const renewed = service.changes('tab-one', renewedController.signal)
  await renewed.next()
  expect(await service.connect('second', 'tab-one')).toMatchObject({ phase: 'live' })
  releaseStop()
  expect(await service.connect('first', 'tab-one')).toMatchObject({ phase: 'live' })
  expect(await service.resolve('second')).toMatchObject({ origin: 'http://127.0.0.1:51078' })
  renewedController.abort()
  await renewed.return(undefined)
})

test('a connect during an SSE outage renews a bounded lease instead of canceling expiry', async () => {
  const { service, forwardChildren } = await sshServiceFixture()
  await service.connect('fixture', 'tab-one')
  const controller = new AbortController()
  const events = service.changes('tab-one', controller.signal)
  await events.next()
  vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] })
  controller.abort()
  await events.next()
  await vi.advanceTimersByTimeAsync(15_000)
  expect(await service.connect('fixture', 'tab-one')).toMatchObject({ phase: 'live' })
  await vi.advanceTimersByTimeAsync(29_999)
  expect(await service.resolve('fixture')).toMatchObject({ origin: 'http://127.0.0.1:51078' })
  await vi.advanceTimersByTimeAsync(1)
  vi.useRealTimers()
  await expect.poll(() => forwardChildren[0]?.signalCode).not.toBeNull()
  expect(await service.connect('fixture', 'other-tab')).toMatchObject({ phase: 'live' })
  await service.disconnect('fixture', 'other-tab')
  await expect(service.resolve('fixture')).rejects.toMatchObject({ code: 'machines.SSH_FORWARD' })
})

test('an active subscriber protects a shared machine when an absent owner expires', async () => {
  const { service, forwardChildren } = await sshServiceFixture()
  const controller = new AbortController()
  const events = service.changes('present', controller.signal)
  await events.next()
  await service.connect('fixture', 'present')
  vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] })
  await service.connect('fixture', 'absent')
  await vi.advanceTimersByTimeAsync(120_000)
  expect(await service.resolve('fixture')).toMatchObject({ origin: 'http://127.0.0.1:51078' })
  expect(forwardChildren[0]?.signalCode).toBeNull()
  vi.useRealTimers()
  await service.disconnect('fixture', 'present')
  await expect(service.resolve('fixture')).rejects.toMatchObject({ code: 'machines.SSH_FORWARD' })
  controller.abort()
  await events.return(undefined)
})

test('a pending connect without an event subscriber expires and stops before forwarding', async () => {
  const { service, commands } = await sshServiceFixture({ slowProbe: true })
  vi.useFakeTimers({ toFake: ['setTimeout', 'clearTimeout'] })
  const connection = service.connect('fixture', 'absent')
  await vi.advanceTimersByTimeAsync(0)
  expect(commands).toHaveLength(1)
  await vi.advanceTimersByTimeAsync(30_000)
  vi.useRealTimers()
  expect(await connection).toMatchObject({ phase: 'idle' })
  expect(commands.some((command) => command.includes('-N'))).toBe(false)
  await expect(service.resolve('fixture')).rejects.toMatchObject({ code: 'machines.SSH_FORWARD' })
})

test('removal revokes shared owners immediately and closes their forward without a browser', async () => {
  const { service, setMachines, forwardChildren } = await sshServiceFixture()
  await service.connect('fixture', 'first-tab')
  await service.connect('fixture', 'second-tab')
  setMachines({})
  const removal = service.reconcile()
  await expect(service.resolve('fixture')).rejects.toMatchObject({ code: 'machines.SSH_SETTINGS' })
  await removal
  expect(forwardChildren[0]?.signalCode).not.toBeNull()
  setMachines({ fixture: machine })
  expect(await service.connect('fixture', 'new-tab')).toMatchObject({ phase: 'live' })
  await service.disconnect('fixture', 'new-tab')
  await expect(service.resolve('fixture')).rejects.toMatchObject({ code: 'machines.SSH_FORWARD' })
})

test('removal cancels a pending launch and does not restore it when the entry is re-added', async () => {
  const { service, setMachines, commands } = await sshServiceFixture({ slowProbe: true })
  const connection = service.connect('fixture', 'departing-tab')
  await expect.poll(() => commands.length).toBe(1)
  setMachines({})
  await service.reconcile()
  expect(await connection).toMatchObject({ phase: 'idle' })
  expect(commands.some((command) => command.includes('-N'))).toBe(false)
  setMachines({ fixture: machine })
  expect(await service.connect('fixture', 'new-tab')).toMatchObject({ phase: 'live' })
  await service.disconnect('fixture', 'new-tab')
  await expect(service.resolve('fixture')).rejects.toMatchObject({ code: 'machines.SSH_FORWARD' })
})

test('replacement revokes the previous target while preserving other owners for the new connection', async () => {
  const { service, setMachines, forwardChildren } = await sshServiceFixture()
  await service.connect('fixture', 'first-tab')
  await service.connect('fixture', 'second-tab')
  setMachines({ fixture: { ...machine, target: 'replacement-host' } })
  const replacement = service.reconcile()
  await expect(service.resolve('fixture')).rejects.toMatchObject({ code: 'machines.SSH_SETTINGS' })
  await replacement
  expect(forwardChildren[0]?.signalCode).not.toBeNull()
  expect(await service.connect('fixture', 'first-tab')).toMatchObject({ phase: 'live' })
  await service.disconnect('fixture', 'first-tab')
  expect(await service.resolve('fixture')).toMatchObject({ origin: 'http://127.0.0.1:51078' })
  await service.disconnect('fixture', 'second-tab')
  await expect(service.resolve('fixture')).rejects.toMatchObject({ code: 'machines.SSH_FORWARD' })
})
