/**
 * Writes the bundled Graphite palette into `packages/ui/src/styles/palette.generated.css`
 * so a page paints Graphite before any script runs. The palette data is the
 * source; this file is its projection. `--check` fails when the two drift.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { bundledPalette, DEFAULT_PALETTE_ID } from '../../packages/contracts/src/index'
import { paletteStylesheet } from '../../packages/client-core/src/themes/palette'

const output = path.join(
  import.meta.dirname,
  '..',
  '..',
  'packages',
  'ui',
  'src',
  'styles',
  'palette.generated.css',
)

const graphite = bundledPalette(DEFAULT_PALETTE_ID)
if (!graphite) {
  console.error(`bundled palette ${DEFAULT_PALETTE_ID} is missing`)
  process.exit(1)
}

// Layered so the runtime <style> the app writes for the selected palette, which
// is unlayered, wins regardless of stylesheet order.
const css = `/* Generated by scripts/themes/generate-palette-css.ts from the bundled Graphite palette. Do not edit. */
@layer palette {
${paletteStylesheet(graphite)
  .trimEnd()
  .split('\n')
  .map((line) => (line.length > 0 ? `  ${line}` : line))
  .join('\n')}
}
`

if (process.argv.includes('--check')) {
  const current = readFileSync(output, 'utf8')
  if (current !== css) {
    console.error('palette.generated.css is stale: run bun run themes:palette-css')
    process.exit(1)
  }
  process.exit(0)
}

writeFileSync(output, css)
console.log(`wrote ${path.relative(process.cwd(), output)}`)
